// Loop principal do jogo, simulação do dia, controle de fases e inicialização
'use strict';

function startGame(isNew,testMode=false){if(isNew&&!testMode&&readSave()&&!confirm('Começar outra história e substituir o progresso atual?'))return;G=isNew?fresh():readSave(testMode);if(G){G.testMode=testMode;if(isNew){G.room=selectedStartingRoom;G.avatarId=$('startingCharacter').value;G.bodegaName=$('startingName').value.trim().slice(0,40)||'Bodega Do Sadi';}if(isNew&&testMode)G.rep=100;}if(!G){say('Não foi possível abrir o salvamento. Comece uma nova história.');return;}started=true;restoreRoutes();paused=false;keys.clear();sparks=[];phoneOpen=false;$('start').classList.add('hidden');$('phone').classList.add('hidden');AudioEngine.unlock();if(G.task?.type==='weigh'){$('weighUI').classList.remove('hidden');updateWeightUI();}refreshHUD();if(G.bocce)showBocce();else if(G.atCancha)showCanchaLobby();else if(G.tvAwardPending)showTelevisionAward();else if(G.game)showCards();else if(isNew)welcome();else openDialog('De volta à bodega','<p>Teu dinheiro, estoque e atendimentos estão guardados. Seus pedidos e escolhas foram preservados. O Guia da bodega explica os sistemas e os próximos desbloqueios.</p><div class="actions"><button class="primary" data-act="close">Retomar</button></div>','resume');save();}

function planDay(){if(!['prep','closed'].includes(G.phase))return;if(G.phase==='prep'){showEvent();return;}const e=EVENTS[plannedEvent().id];openDialog('Amanhã na bodega',`<p>Dia ${G.day+1} · ${difficulty(G.day+1).label}</p><div class="callout"><b>${e.icon} ${e.name}</b><p>${e.desc}</p></div><p>${e.prep}</p><p>Os eventos são sorteados e não se repetem em dias seguidos. A previsão fica guardada até você avançar.</p><button class="primary" data-act="chooseEvent" data-id="automatic">Preparar o próximo dia</button>`,'planning');}

function chooseDayEvent(id){if(G.phase==='closed'){nextDay('automatic');return;}if(G.phase==='prep')showEvent();}

function openDay(){if(G.phase==='closed'){nextDay();return;}if(G.phase==='prep'){if(tutorialActive())G.event.seen=true;if(!G.event.seen){showEvent();return;}G.shopVisits=0;G.phase='open';fixedTableModes();G.elapsed=0;G.spawnShop=2;G.spawnGroup=G.day===1?22:10;G.report=null;G.event.fired={};G.puddles=[];G.tournament=null;if(championshipActive())startTournament();say(eventInfo().name+' · portas abertas!');AudioEngine.ready();save();return;}if(G.phase==='open'){if(tutorialActive()){say('Conclua a etapa do tutorial: o primeiro dia termina depois das lições.');return;}G.phase='closing';say('Portas fechadas. Conclua os atendimentos que já chegaram.');save();}else if(confirm('Encerrar agora? Os pedidos ainda não pagos serão cancelados.'))finishDay(true);}

function nextDay(eventId){if(G.bocce||G.game||G.phase!=='closed')return;if(eventId===undefined){planDay();return;}const next=eventId==='automatic'?plannedEvent():{id:eventId,seen:false,fired:{}};G.day++;G.tv=true;G.nextEvent=null;G.tournament=null;G.phase='prep';G.elapsed=0;G.report=null;G.stats=stats(G.cash);G.cardRewards=0;G.boost=0;G.slow=0;G.puddles=[];G.fightTarget=null;for(const t of G.tables)t.fight=null;G.event=next;fixedTableModes();G.player={x:515,y:600,dx:0,dy:1,walk:false};if(G.legacyDebt){G.cash+=G.legacyDebt;G.stats.aid+=G.legacyDebt;G.legacyDebt=0;}closeDialog(true);save();refreshHUD();showEvent();}

function finishDay(force=false){if(G.phase==='closed')return;if(G.task?.type==='weigh')abandonWeigh();cancelHold();if(force){G.phase='closing';for(const g of [...G.groups])if(g.state!=='leave')departGroup(g,true);G.groups=[];G.shop=[];G.cardRound=null;}clearUnserved();const operating=round(Math.max(2,8*Math.min(G.elapsed/DAY,1)));G.stats.expenses=round(operating+(G.stats.breakage||0));spendCash(operating);G.fightTarget=null;for(const t of G.tables)t.fight=null;updateFightUI();G.phase='closed';G.report={...G.stats,end:G.cash,profit:round(G.stats.revenue+G.stats.tips-G.stats.cogs-G.stats.waste-G.stats.expenses)};awardTelevision();save();if(G.tvAwardPending)showTelevisionAward();else showReport();}

function showReport(){const r=G.report;if(!r)return;openDialog('Fechou o caixa. Ficaram os causos.',`<p>Dia ${G.day} · ${r.served} atendimentos pagos · ${r.lost} desistências.</p><div class="receipt"><span>Vendas</span><span>${money(r.revenue)}</span><span>Gorjetas</span><span>${money(r.tips)}</span><span>− Mercadorias servidas</span><span>${money(r.cogs)}</span><span>− Desperdício</span><span>${money(r.waste)}</span><span>− Luz, despesas e quebras</span><span>${money(r.expenses)}</span><strong>Lucro operacional</strong><strong class="${r.profit>=0?'good':'bad'}">${money(r.profit)}</strong></div><div class="grid"><div class="panel"><h3>Dinheiro no caixa</h3><p>${money(r.start)} iniciais + vendas + gorjetas + ${money(r.aid)} de ajuda − ${money(r.purchases)} em compras − ${money(r.investments)} em melhorias − despesas + ${money(r.cardReturns||0)} retornados do truco − ${money(r.cardStakes||0)} apostados.</p><p><b>Saldo do truco: ${money((r.cardReturns||0)-(r.cardStakes||0))}</b></p><p><b>Saldo da bocha: ${money((r.bocceReturns||0)-(r.bocceStakes||0))}</b> · ${money(r.bocceReturns||0)} retornados − ${money(r.bocceStakes||0)} apostados</p><b>${money(r.end)}</b></div><div class="panel"><h3>Quem veio, gostou?</h3><p>Satisfação média: ${r.served?Math.round(r.satisfaction/r.served)+'%':'sem atendimentos'}.</p><p>Estoque comprado só entra no lucro quando é servido ou descartado. Dinheiro no caixa e lucro são diferentes.</p></div></div><div class="actions"><button class="primary" data-act="nextDay">Preparar o próximo dia</button><button data-act="close">Ficar na bodega</button><button data-act="save">Salvar</button></div>`,'report');}

function showEvent(){const e=eventInfo();openDialog('Hoje: '+e.name,`<div class="event-card"><span class="event-symbol">${e.icon}</span><div><h3>Dia ${G.day} · previsão do movimento</h3><p>${e.desc}</p></div></div><div class="callout"><b>Prepare antes de abrir</b><br>${e.prep}</div><p>${G.tv?'📺 TV da comunidade instalada · eventos de futebol disponíveis.':''}</p><p>${G.event.id==='motos'?'Encomenda confirmada: 2 xis salada + 2 refrigerantes. A turma chega aos 50 segundos de expediente.':''}</p><div class="actions"><button class="primary" data-act="openConfirmed">${G.phase==='prep'?'Entendi · abrir a bodega':'Voltar ao jogo'}</button><button data-act="planBuy">Organizar estoque no celular</button><button data-act="close">Continuar preparando</button></div>`,'event');}

function eventForDay(day,state=G){
 if(day===1)return {id:'normal',seen:false,fired:{}};
 const previous=state?.event?.id,all=Object.keys(EVENTS).filter(id=>day>=2||!['gremio','inter','grenal'].includes(id));
 let bag=(state?.eventBag||[]).filter(id=>all.includes(id));
 if(!bag.length){bag=[...all];for(let i=bag.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[bag[i],bag[j]]=[bag[j],bag[i]];}}
 if(bag[bag.length-1]===previous){const alternative=bag.findIndex(id=>id!==previous);if(alternative>=0)[bag[alternative],bag[bag.length-1]]=[bag[bag.length-1],bag[alternative]];else bag=all.filter(id=>id!==previous);}
 const id=bag.pop();if(state)state.eventBag=bag;return {id,seen:false,fired:{}};
}

function eventInfo(){return EVENTS[G.event.id]||EVENTS.normal;}

function orderable(k,n=1){return unlocked(k)&&G.stock[k]+G.deliveries.filter(d=>d.key===k).reduce((sum,d)=>sum+d.qty,0)>=n;}

function eventTick(dt){G.boost=Math.max(0,G.boost-dt);G.weatherClock+=dt;for(const v of G.visual)v.life-=dt;G.visual=G.visual.filter(v=>v.life>0);if(G.phase!=='open')return;const e=G.event;
 if(e.id==='radio'&&G.elapsed>=75&&!e.fired.interval){e.fired.interval=true;let count=0;for(const g of G.groups){if(!['seated','chat'].includes(g.state))continue;addDinerRound(g);count++;}if(!count){spawnGroup({special:'intervalo',fixedOrders:['cerveja','refri'],size:2});}say('Intervalo no rádio! A turma pediu rodadas juntas.');AudioEngine.crowd();}
 if(e.id==='motos'&&G.elapsed>=35&&!e.fired.warning){e.fired.warning=true;say('Celular: os motociclistas chegam em 15 s. São 2 xis e 2 refrigerantes.');AudioEngine.phone();}
 if(e.id==='motos'&&G.elapsed>=50&&!e.fired.group){const g=spawnGroup({special:'motociclistas',fixedOrders:['xis_salada','xis_salada','refri','refri'],size:2});if(g){e.fired.group=true;say('A turma das motos chegou com a encomenda!');AudioEngine.crowd();}}
 if(e.id==='baile'&&G.elapsed>=75&&!e.fired.quiet){e.fired.quiet=true;say('Começou o baile. Agora o movimento dá uma folga.');AudioEngine.ready();}
 footballTick(dt);
}

function deliveryTick(dt){for(const d of G.deliveries){d.left-=dt;if(d.left<=0){const units=G.stock[d.key];G.avg[d.key]=(G.avg[d.key]*units+d.cost)/(units+d.qty);G.stock[d.key]+=d.qty;deliveryVisitor=3.5;effect('Entrega! +'+d.qty+' '+nameOf(d.key),875,718,'#e5f0bc');AudioEngine.ready();}}G.deliveries=G.deliveries.filter(d=>d.left>0);deliveryVisitor=Math.max(0,deliveryVisitor-dt);}

function progressionTick(dt){G.slow=Math.max(0,G.slow-dt);if(G.puddles.some(p=>Math.hypot(p.x-G.player.x,p.y-G.player.y)<p.r)){if(G.slow===0)effect('Pés molhados · 8 s',G.player.x,G.player.y-90,'#b6dced');G.slow=8;}G.talkCooldown=G.talkCooldown.map(n=>Math.max(0,n-dt));if(G.dialogue){G.dialogue.life-=dt;if(G.dialogue.life<=0){advanceDialogue();}}for(const t of availableTables()){t.fightCooldown=Math.max(0,(t.fightCooldown||0)-dt);if(t.fight){t.fight.left-=dt;t.fight.age+=dt;if(t.fight.left<=0)resolveFight(t,false);continue;}const g=G.groups.find(g=>g.id===t.group);if(fightsAllowed()&&G.event.id==='campeonato'&&G.phase==='open'&&g&&g.size>1&&isTableTruco(t)&&['seated','chat'].includes(g.state)&&!t.fightCooldown){g.trucoAge=(g.trucoAge||0)+dt;if(g.trucoAge>=(G.event.id==='campeonato'?10:16)){g.trucoAge=0;const chance=Math.max(.35,(G.event.id==='campeonato'?.95:isTrucoNight()?.8:.65)-(G.friends[g.person]||0)*.0015);if(Math.random()<chance)triggerFight(t);}}}if(G.fightTarget!==null)updateFightUI();}

function simulate(dt){if(!started||paused||modal||G.game||G.bocce||G.atCancha||document.hidden)return;let dx=0,dy=0;if(!phoneOpen&&!G.task&&G.fightTarget===null){dx=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0);dy=(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0);}const len=Math.hypot(dx,dy);G.player.walk=!!len;if(len){dx/=len;dy/=len;G.player.dx=dx;G.player.dy=dy;const step=BASE_SPEED*(1+movementBonus())*(G.boost>0?1+mateStats().bonus:1)*(G.slow>0?.65:1)*dt;for(let n=0;n<4;n++){const x=G.player.x+dx*step/4,y=G.player.y+dy*step/4;if(canWalk(x,G.player.y))G.player.x=x;if(canWalk(G.player.x,y))G.player.y=y;}}
 progressionTick(dt);eventTick(dt);kitchenTick(dt);deliveryTick(dt);holdTick(dt);for(const f of G.floor){if(!f.item.spoiled){f.item.floorLeft=Math.max(0,f.item.floorLeft-dt);if(f.item.floorLeft<=0){f.item.spoiled=true;effect('Estragou',f.x,f.y-28,'#e4b085');}}}for(const e of sparks)e.life-=dt;sparks=sparks.filter(e=>e.life>0);
 if(G.phase==='open'||G.phase==='closing'){customersTick(dt);if(tutorialActive()){tutorialTick();return;}if(G.phase==='open'){G.elapsed+=dt;tournamentTick();G.spawnShop-=dt;G.spawnGroup-=dt;if(G.spawnShop<=0&&!championshipActive()){spawnShop();G.spawnShop=arrivalInterval('shop');}if(G.spawnGroup<=0&&!championshipActive()){spawnGroup();G.spawnGroup=arrivalInterval('group');}if(G.elapsed>=DAY){G.elapsed=DAY;G.phase='closing';say('Hora de fechar. Sem novas chegadas; conclua os pedidos restantes.');}}else if(!G.groups.length&&!G.shop.length&&!G.cardRound)finishDay();}
}

function pauseGame(reason='Uma pausa para o mate.'){if(!started)return;if(G.bocce){toggleBoccePause(true);return;}keys.clear();pointerHold=false;if(G.task?.type!=='weigh')cancelHold();paused=true;openDialog('A bodega está pausada',`<p>${reason}</p><p>Nenhuma fila, preparo, entrega ou validade avança durante a pausa.</p><div class="actions"><button class="primary" data-act="resume">Retomar o jogo</button><button data-act="save">Salvar progresso</button></div>`,'pause');save();}

function resumeGame(){paused=false;if(G.game)showCards();else closeDialog(true);AudioEngine.unlock();}

function frame(time){const dt=Math.min(.05,Math.max(0,(time-lastFrame)/1000));lastFrame=time;const running=started&&!paused&&!modal&&!G.game&&!document.hidden;if(running)frameClock+=dt;if(G.bocce){bocceTick(dt);drawBocce();}else if(G.atCancha){drawCanchaLobby();}else{simulate(dt);draw();}AudioEngine.update(dt);hudClock+=dt;phoneClock+=dt;saveClock+=dt;if(hudClock>.16){hudClock=0;refreshHUD();}if(phoneOpen&&phoneClock>.5){phoneClock=0;const y=$('phoneContent').scrollTop,b=document.activeElement,focus=b?.closest('#phoneContent')?{act:b.dataset.act,id:b.dataset.id}:null;renderPhone();$('phoneContent').scrollTop=y;if(focus){const btn=[...$('phoneContent').querySelectorAll('[data-act]')].find(e=>e.dataset.act===focus.act&&e.dataset.id===focus.id);btn?.focus({preventScroll:true});}}if(saveClock>12){saveClock=0;save();}requestAnimationFrame(frame);}
