// Loop principal do jogo, simulação do dia, controle de fases e inicialização
'use strict';

function startGame(isNew,testMode=false){if(isNew&&!testMode&&readSave()&&!confirm('Começar outra história e substituir o progresso atual?'))return;G=isNew?fresh():readSave(testMode);if(G){G.testMode=testMode===true;G.eventMode=testMode==='eventos';if(isNew&&G.eventMode){G.tutorial.guided=false;G.tutorial.complete=true;}if(isNew){G.avatarId='sadi';G.bodegaName=$('startingName').value.trim().slice(0,40)||'Bodega Do Sadi';}}if(!G){say('Não foi possível abrir o salvamento. Comece uma nova história.');return;}started=true;restoreRoutes();paused=false;keys.clear();sparks=[];phoneOpen=false;$('start').classList.add('hidden');$('phone').classList.add('hidden');AudioEngine.unlock();if(G.task?.type==='weigh'){$('weighUI').classList.remove('hidden');updateWeightUI();}refreshHUD();if(G.bocce)showBocce();else if(G.atCancha)showCanchaLobby();else if(G.tvAwardPending)showTelevisionAward();else if(G.game)showCards();else if(isNew){if(G.testMode)welcome();else if(G.eventMode)showEvent();else startIntro();}else openDialog('De volta à bodega','<p>Teu dinheiro, estoque e atendimentos estão guardados. Seus pedidos e escolhas foram preservados. O Guia da bodega explica os sistemas e os próximos desbloqueios.</p><div class="actions"><button class="primary" data-act="close">Retomar</button></div>','resume');save();}

function planDay(){if(!['prep','closed'].includes(G.phase))return;if(G.phase==='prep'){showEvent();return;}const e=EVENTS[plannedEvent().id];openDialog('Amanhã na bodega',`<p>Dia ${G.day+1} · ${difficulty(G.day+1).label}</p><div class="callout"><b>${e.icon} ${e.name}</b><p>${e.desc}</p></div><p>${e.prep}</p>${weekPreview(G.day+1)}${(G.testMode||G.eventMode)?`<div class="panel test-event"><h3>Modo de testes · escolher o evento</h3><select id="testEvent">${Object.entries(EVENTS).map(([id,v])=>`<option value="${id}" ${id===plannedEvent().id?'selected':''}>${v.icon} ${v.name}</option>`).join('')}<option value="lasso">🐂 Laçar gado (agora)</option></select><button data-act="chooseTestEvent">Usar este evento amanhã</button></div>`:''}<button class="primary" data-act="chooseEvent" data-id="automatic">Preparar o próximo dia</button>`,'planning');}

function chooseDayEvent(id){if(G.phase==='closed'){nextDay('automatic');return;}if(G.phase==='prep')showEvent();}
// Modo de testes (dinheiro infinito): escolhe o evento do próximo dia.
function chooseTestEvent(id){if(!G.testMode&&!G.eventMode||G.phase!=='closed')return;if(id==='lasso'){if(!G.herd)G.herd=1;startLasso();return;}if(!EVENTS[id])return;G.nextEvent={id,seen:false,fired:{}};save();say('Amanhã: '+EVENTS[id].name+'.');planDay();}

function openDay(){if(G.phase==='closed'){nextDay();return;}if(G.phase==='prep'){if(tutorialActive())G.event.seen=true;if(!G.event.seen){showEvent();return;}G.shopVisits=0;G.phase='open';fixedTableModes();G.elapsed=0;G.spawnShop=2;G.spawnGroup=G.day===1?22:10;G.report=null;G.event.fired={};G.puddles=[];G.tournament=null;if(championshipActive())startTournament();say(eventInfo().name+' · portas abertas!');AudioEngine.ready();if(G.event.id==='costelao')costelaoWelcome();save();return;}if(G.phase==='open'){if(tutorialActive()){say('Conclua a etapa do tutorial: o primeiro dia termina depois das lições.');return;}dailyFinale();if(G.event.id==='campeonato'&&!G.tournament?.finished){say('Aguarde as duplas sentarem para anunciar o resultado e servir a rodada final.');return;}G.phase='closing';for(const g of G.groups)if(g.state==='chat')g.chat=Math.min(g.chat,8);say('Portas fechadas. Conclua os atendimentos que já chegaram.');save();}else if(confirm('Encerrar agora? Os pedidos ainda não pagos serão cancelados.'))finishDay(true);}

function nextDay(eventId){if(G.bocce||G.game||G.lasso||G.phase!=='closed')return;if(G.giftQueue?.length){if(G.challengeVisit?.arrived&&G.challengeVisit.kind==='gift'&&!G.challengeVisit.leaving)showGiftVisit();else startGiftVisit();return;}if(sportState().challenge){if(G.challengeVisit?.arrived&&G.challengeVisit.kind!=='gift'&&!G.challengeVisit.leaving)showSportChallenge();else startChallengeVisit();return;}if(lassoNeeded()){if(!G.lassoTaught&&!G.lassoSceneSeen&&scenesEnabled()){G.lassoSceneSeen=true;G.herd=Math.max(G.herd||0,1);playScene('sabado',()=>lassoIntro());}else lassoIntro();return;}if(eventId===undefined){planDay();return;}const next=eventId==='automatic'?plannedEvent():{id:eventId,seen:false,fired:{}};G.day++;G.tv=true;G.nextEvent=null;G.tournament=null;G.phase='prep';G.elapsed=0;G.report=null;G.stats=stats(G.cash);G.cardRewards=0;G.boost=0;G.slow=0;G.puddles=[];G.fightTarget=null;for(const t of G.tables)t.fight=null;G.event=next;fixedTableModes();G.player={x:520,y:720,dx:0,dy:1,walk:false};campoState().tutorial=null;if(G.legacyDebt){G.cash+=G.legacyDebt;G.stats.aid+=G.legacyDebt;G.legacyDebt=0;}processFiado();closeDialog(true);save();refreshHUD();showEvent();}

function finishDay(force=false){if(G.phase==='closed')return;if(G.task?.type==='weigh')abandonWeigh();if(G.event.id==='costelao')discardCostelao();cancelHold();if(force){G.phase='closing';for(const g of [...G.groups])if(g.state!=='leave')departGroup(g,true);G.groups=[];G.shop=[];G.cardRound=null;}clearUnserved();const{power,rent,supplies}=dailyCosts();G.stats.power=power;G.stats.rent=rent;G.stats.supplies=supplies;G.stats.expenses=round(power+rent+supplies+(G.stats.breakage||0));spendCash(power+rent+supplies);G.fightTarget=null;for(const t of G.tables)t.fight=null;updateFightUI();G.phase='closed';G.report={...G.stats,end:G.cash,profit:round(G.stats.revenue+G.stats.tips+(G.stats.fiadoIn||0)-G.stats.cogs-G.stats.waste-G.stats.expenses)};G.report.xp=Math.max(0,Math.round(G.report.profit/4));gainXP(G.report.xp);prepareAfterHours();awardTelevision();progressCheck();save();if(G.tvAwardPending)showTelevisionAward();else showReport();}

function showReport(){const r=G.report;if(!r)return;
 const row=(label,value,always=false)=>value||always?`<span>${label}</span><span>${money(value||0)}</span>`:'';
 const truco=(r.cardReturns||0)-(r.cardStakes||0),bocha=(r.bocceReturns||0)-(r.bocceStakes||0);
 openDialog('Fechou o caixa',`<p>Dia ${G.day} · ${r.served} atendimentos · ${r.lost} desistências · satisfação ${r.served?Math.round(r.satisfaction/r.served)+'%':'—'}</p><div class="receipt">${row('Vendas',r.revenue,true)}${row('Gorjetas',r.tips)}${row('Fiado recebido',r.fiadoIn||0)}${row('− Mercadorias servidas',r.cogs)}${row('− Desperdício',r.waste)}${row('− Aluguel',r.rent||0)}${row('− Luz e querosene',r.power||0)}${row('− Lenha e sal',r.supplies||0)}${row('− Quebras',r.breakage||0)}<strong>Lucro do dia</strong><strong class="${r.profit>=0?'good':'bad'}">${money(r.profit)}</strong></div><p>Caixa: ${money(r.start)} → <b>${money(r.end)}</b>${truco?' · truco '+money(truco):''}${bocha?' · bocha '+money(bocha):''}${r.credit?' · fiado anotado '+money(r.credit):''}${r.fiadoLost?' · calote '+money(r.fiadoLost):''} · <b>+${r.xp||0} XP</b></p><div class="actions"><button class="primary" data-act="nextDay">Preparar o próximo dia</button><button data-act="close">Ficar na bodega</button></div>`,'report');}

function showEvent(){const e=eventInfo();openDialog('Hoje: '+e.name,`<div class="event-card"><span class="event-symbol">${e.icon}</span><div><h3>Dia ${G.day} · ${calendar().label}</h3><p>${e.desc}</p></div></div>${weekPreview()}<div class="callout"><b>Prepare antes de abrir</b><br>${e.prep}</div>${G.tv&&isFootball()?'<p>📺 Dia de jogo: a TV vai para a parede.</p>':''}<div class="actions"><button class="primary" data-act="openConfirmed">${G.phase==='prep'?'Abrir a bodega':'Voltar ao jogo'}</button><button data-act="planBuy">Abrir o celular</button><button data-act="close">Continuar preparando</button></div>`,'event');}

function eventForDay(day,state=G){
 // Dias fixos do calendário gaúcho; nos outros, sorteio sem repetir o dia anterior.
 const fixed=fixedEventFor(day);if(fixed)return {id:fixed,seen:false,fired:{}};
 const previous=state?.event?.id,all=randomEventPool(day);
 let bag=(state?.eventBag||[]).filter(id=>all.includes(id));
 if(!bag.length){bag=[...all];for(let i=bag.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[bag[i],bag[j]]=[bag[j],bag[i]];}}
 if(bag[bag.length-1]===previous){const alternative=bag.findIndex(id=>id!==previous);if(alternative>=0)[bag[alternative],bag[bag.length-1]]=[bag[bag.length-1],bag[alternative]];else bag=all.filter(id=>id!==previous);}
 const id=bag.pop();if(state)state.eventBag=bag;return {id,seen:false,fired:{}};
}

function eventInfo(){return EVENTS[G.event.id]||EVENTS.normal;}

function orderable(k,n=1){return unlocked(k)&&G.stock[k]+G.deliveries.filter(d=>d.key===k).reduce((sum,d)=>sum+d.qty,0)>=n;}

function eventTick(dt){G.boost=Math.max(0,G.boost-dt);G.weatherClock+=dt;for(const v of G.visual)v.life-=dt;G.visual=G.visual.filter(v=>v.life>0);if(G.phase!=='open')return;const e=G.event;
 if(e.id==='radio'&&G.elapsed>=75&&!e.fired.interval){e.fired.interval=true;let count=0;for(const g of G.groups){if(!['seated','chat'].includes(g.state))continue;addDinerRound(g);count++;}if(!count){spawnGroup({special:'intervalo',fixedOrders:['cerveja','refri'],size:2});}say('Intervalo no rádio! A turma pediu rodadas juntas.');AudioEngine.crowd();}
 if(e.id==='baile'&&G.elapsed>=75&&!e.fired.quiet){e.fired.quiet=true;say('Começou o baile. Agora o movimento dá uma folga.');AudioEngine.ready();}
 footballTick(dt);
}

function deliveryTick(dt){for(const d of G.deliveries){d.left-=dt;if(d.left<=0){const units=G.stock[d.key];G.avg[d.key]=(G.avg[d.key]*units+d.cost)/(units+d.qty);G.stock[d.key]+=d.qty;deliveryVisitor=DELIVERY_TIME;effect('Entrega! +'+d.qty+' '+nameOf(d.key),ENTRY.x-10,ENTRY.y-65,'#e5f0bc');AudioEngine.horn();}}G.deliveries=G.deliveries.filter(d=>d.left>0);deliveryVisitor=Math.max(0,deliveryVisitor-dt);}

function progressionTick(dt){G.slow=Math.max(0,G.slow-dt);if(G.puddles.some(p=>Math.hypot(p.x-G.player.x,p.y-G.player.y)<p.r)){if(G.slow===0)effect('Pés molhados · 8 s',G.player.x,G.player.y-90,'#b6dced');G.slow=8;}G.talkCooldown=G.talkCooldown.map(n=>Math.max(0,n-dt));if(G.dialogue){G.dialogue.life-=dt;if(G.dialogue.life<=0){advanceDialogue();}}for(const t of availableTables()){t.fightCooldown=Math.max(0,(t.fightCooldown||0)-dt);if(t.fight){t.fight.left-=dt;t.fight.age+=dt;if(t.fight.left<=0)resolveFight(t,false);continue;}const g=G.groups.find(g=>g.id===t.group);if(fightsAllowed()&&G.event.id==='campeonato'&&G.phase==='open'&&g&&g.size>1&&isTableTruco(t)&&['seated','chat'].includes(g.state)&&!t.fightCooldown){g.trucoAge=(g.trucoAge||0)+dt;if(g.trucoAge>=(G.event.id==='campeonato'?10:16)){g.trucoAge=0;const chance=Math.max(.35,(G.event.id==='campeonato'?.95:.65)-(G.friends[g.person]||0)*.0015);if(Math.random()<chance)triggerFight(t);}}}if(G.fightTarget!==null)updateFightUI();}

function simulate(dt){if(!started||paused||modal||G.game||G.bocce||G.atCancha||document.hidden)return;let dx=0,dy=0;if(!phoneOpen&&!G.task&&G.fightTarget===null){dx=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0);dy=(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0);}const len=Math.hypot(dx,dy);G.player.walk=!!len;if(len){dx/=len;dy/=len;G.player.dx=dx;G.player.dy=dy;const step=BASE_SPEED*(1+movementBonus())*(G.boost>0?1+mateStats().bonus:1)*(G.slow>0?.65:1)*dt;for(let n=0;n<4;n++){const x=G.player.x+dx*step/4,y=G.player.y+dy*step/4;if(canWalk(x,G.player.y))G.player.x=x;if(canWalk(G.player.x,y))G.player.y=y;}}
 progressionTick(dt);fxTick(dt);challengeVisitTick(dt);eventTick(dt);kitchenTick(dt);campoTick(dt);mixTick(dt);deliveryTick(dt);holdTick(dt);for(const f of G.floor){if(!f.item.spoiled){f.item.floorLeft=Math.max(0,f.item.floorLeft-dt);if(f.item.floorLeft<=0){f.item.spoiled=true;effect('Estragou',f.x,f.y-28,'#e4b085');}}}for(const e of sparks)e.life-=dt;sparks=sparks.filter(e=>e.life>0);
 if(G.phase==='open'||G.phase==='closing'){const toastTraining=toastLessonTick();customersTick(dt);if(toastTraining)return;if(tutorialActive()){tutorialTick();return;}if(costelaoTutorialActive()){costelaoTutorialTick();return;}if(G.phase==='open'){G.elapsed+=dt;tournamentTick();G.spawnShop-=dt;G.spawnGroup-=dt;if(G.spawnShop<=0&&!championshipActive()){spawnShop();G.spawnShop=arrivalInterval('shop');}if(G.spawnGroup<=0&&!championshipActive()){spawnGroup();G.spawnGroup=arrivalInterval('group');}if(G.elapsed>=DAY){G.elapsed=DAY;dailyFinale();G.phase='closing';for(const g of G.groups)if(g.state==='chat')g.chat=Math.min(g.chat,8);say('Hora de fechar. Sem novas chegadas; conclua os pedidos restantes.');}}else if(!G.groups.length&&!G.shop.length&&!G.cardRound)finishDay();}
}

// Menu do Esc: salvar, volumes de música, ambiente e efeitos, progresso, jogo novo e menu inicial.
function volumeSlider(kind,label){const v=Math.round(AudioEngine[kind+'Vol']*100);return `<label class="volume-row"><span>${label}</span><input type="range" min="0" max="100" step="5" value="${v}" data-volume="${kind}" aria-label="${label}"><output>${v}%</output></label>`;}
function pauseGame(reason=''){if(!started)return;if(G.bocce){toggleBoccePause(true);return;}keys.clear();pointerHold=false;if(G.task?.type!=='weigh')cancelHold();paused=true;openDialog('Menu do jogo',`${reason?`<p>${reason}</p>`:''}<div class="game-menu"><button class="primary" data-act="resume">Continuar jogando</button><button data-act="save">Salvar jogo</button><button data-act="menuProgress">Ver progresso</button><button data-act="menuNew">Iniciar novo jogo</button><button data-act="mainMenu">Menu inicial</button></div><div class="panel volume-panel"><h3>Som</h3>${volumeSlider('music','Música')}${volumeSlider('ambient','Sons ambiente')}${volumeSlider('fx','Efeitos')}</div>`,'pause');save();}
// Volta para a tela inicial: o jogo fica salvo e a tela oferece continuar.
function showMainMenu(){if(started)save();if(phoneOpen)togglePhone(false);closeDialog(true);started=false;paused=false;keys.clear();['lassoUI','weighUI','mixUI','chopUI','pourUI','fightUI'].forEach(id=>$(id)?.classList.add('hidden'));$('continue').disabled=!readSave();$('start').classList.remove('hidden');AudioEngine.syncMusic();}

function resumeGame(){paused=false;if(G.game)showCards();else closeDialog(true);AudioEngine.unlock();}

// Pausado, com diálogo aberto ou na tela inicial, a cena fica parada: redesenha só 4 vezes por segundo.
// Se o computador não segura ~40 quadros por segundo, o desenho passa a usar resolução 1:1 (modo leve).
function adaptGraphics(dt){frameAverage=frameAverage*.95+dt*.05;slowClock=frameAverage>1/40?slowClock+dt:0;if(slowClock>4)lightGraphics=true;}

// Um erro num quadro não pode congelar o jogo: o erro é reportado e o próximo quadro segue.
function frame(time){try{frameStep(time);}catch(error){setTimeout(()=>{throw error;});}requestAnimationFrame(frame);}
function frameStep(time){const dt=Math.min(.05,Math.max(0,(time-lastFrame)/1000));lastFrame=time;const running=started&&!paused&&!modal&&!G.game&&!document.hidden;if(running)frameClock+=dt;if(scene){if(running)sceneTick(dt);if(scene)drawScene();else draw();}else if(G.lasso){if(running)lassoTick(dt);drawLasso();}else if(G.bocce){bocceTick(dt);drawBocce();}else if(G.atCancha){drawCanchaLobby();}else{simulate(dt);idleDrawClock+=dt;if(running||idleDrawClock>.25){idleDrawClock=0;draw();}}if(running)adaptGraphics(dt);sportTalkTick(dt);if(started&&!paused)progressTick(dt);AudioEngine.update(dt);hudClock+=dt;phoneClock+=dt;saveClock+=dt;if(hudClock>.16){hudClock=0;refreshHUD();}if(phoneOpen&&phoneClock>.5){phoneClock=0;const y=$('phoneContent').scrollTop,b=document.activeElement,focus=b?.closest('#phoneContent')?{act:b.dataset.act,id:b.dataset.id}:null;renderPhone();$('phoneContent').scrollTop=y;if(focus){const btn=[...$('phoneContent').querySelectorAll('[data-act]')].find(e=>e.dataset.act===focus.act&&e.dataset.id===focus.id);btn?.focus({preventScroll:true});}}if(saveClock>12){saveClock=0;save();}}
