// Gerenciamento de estado global, persistência e inicialização
'use strict';

// Criado pelo bootstrap, depois que todos os scripts estiverem disponíveis.
let G = null,
    started = false,
    paused = false,
    modal = null,
    phoneOpen = false,
    phoneTab = 'supplier',
    phoneCat = 'Cozinha',
    keys = new Set(),
    pointerHold = false,
    notices = [],
    sparks = [],
    deliveryVisitor = 0,
    frameClock = 0,
    lastFrame = 0,
    saveClock = 0,
    hudClock = 0,
    phoneClock = 0,
    walkCycle = 0;

let cardInvite = null;

const trucoRules=`<details class="rules"><summary>Regras desta mesa · Truco gaúcho</summary><p>Truco cego, adaptado para <b>1 contra 1 e partida curta a 6 tentos</b>. Baralho espanhol de 40 cartas (1 a 7, 10, 11, 12), três cartas por pessoa. <b>Sem envido, flor ou amostra nesta versão.</b> O mão alterna a cada rodada. Quem vence uma vaza abre a seguinte; se empatar, quem abriu continua abrindo.</p><p>Da maior à menor: <b>1 de espadas &gt; 1 de bastos &gt; 7 de espadas &gt; 7 de ouros &gt; todos os 3 &gt; todos os 2 &gt; 1 de copas/ouros &gt; 12 &gt; 11 &gt; 10 &gt; 7 de copas/bastos &gt; 6 &gt; 5 &gt; 4</b>.</p><p>Duas vazas ganham a rodada. Se a primeira empata, vale a próxima vaza com vencedor. Se a segunda ou terceira empata, vence quem ganhou a primeira. Se todas empatam, vence o mão. A rodada vale 1; truco aceito vale 2, retruco 3, vale quatro 4. Recusar concede o valor anterior ao pedido. Só quem aceitou o último aumento pode pedir o próximo. Nesta mesa, pede-se antes de jogar a própria carta. Correr concede o valor em vigor.</p><p>Hierarquia e empates baseados no regulamento de Truco Cego da CBTG; duração, número de jogadores e ausência de envido/flor são adaptações desta mesa.</p></details>`;
const cachetaRules=`<details class="rules"><summary>Regras desta mesa · Cacheta</summary><p>Variante curta de <b>nove cartas, dois baralhos de 52 cartas, sem curingas</b>, contra um adversário. Comece comprando uma carta do monte ou a carta visível do descarte. Com dez cartas, escolha uma para descartar. Não se pode devolver imediatamente a mesma carta comprada do descarte.</p><p>Para bater, as nove cartas restantes precisam formar <b>três jogos de exatamente três cartas</b>: trincas do mesmo valor com três naipes diferentes, ou sequências consecutivas do mesmo naipe. O ás vale somente 1 (A–2–3 vale; Q–K–A não). Cartas idênticas dos dois baralhos não podem compor uma mesma trinca. Esta variante não usa encaixes na mesa nem jogos de quatro cartas.</p><p>A verificação de vitória é automática após cada descarte, para os dois jogadores. O descarte é reciclado quando o monte acaba, mantendo a carta do topo. Após 60 turnos de cada jogador sem batida, há empate. A IA avalia apenas suas cartas e o descarte visível.</p></details>`;

function stats(cash){return{start:cash,revenue:0,cogs:0,purchases:0,waste:0,expenses:0,breakage:0,tips:0,aid:0,investments:0,cardStakes:0,cardReturns:0,bocceStakes:0,bocceReturns:0,served:0,lost:0,satisfaction:0};}

function fresh(){const g={version:12,eventBag:[],nextEvent:null,atCancha:false,tvAwardPending:false,mateEmptyNotified:false,avatarId:'sadi',bodegaName:'Bodega Do Sadi',bocce:null,room:1,mateHerb:500,tv:false,testMode:false,dialogueSeen:[],day:1,cash:248,rep:60,xp:0,phase:'prep',elapsed:0,up:{},boost:0,gear:'feet',slow:0,talkCooldown:PEOPLE.map(()=>0),conversations:PEOPLE.map(()=>0),storyCursor:PEOPLE.map(()=>0),dialogue:null,dialogueQueue:[],tournament:null,fightTarget:null,shopVisits:0,regulars:PEOPLE.map(()=>0),event:eventForDay(1),puddles:[],visual:[],weatherClock:0,stock:{},avg:{},returnedItems:{},player:{x:515,y:586,dx:0,dy:1,walk:false},hands:[null,null],slot:0,kitchen:{grill:[null,null,null],bench:[null,null],press:null,parking:[null,null]},floor:[],deliveries:[],groups:[],shop:[],tables:TABLE_DEF.map(t=>({...t,group:null,dirty:false,plates:0,mode:t.id===1?'truco':'restaurant',fight:null,fightCooldown:0})),cardRound:null,cardTimer:55,next:1,spawnShop:3,spawnGroup:22,task:null,stats:stats(248),friends:PEOPLE.map(()=>0),cardWins:0,cardRewards:0,cosmetic:false,game:null,aidDay:0,tutorial:{guided:true,step:0,introduced:false,actor:null,delivered:false,complete:false,shop:false,table:false,xis:false,phone:false},totalServed:0,report:null};for(const[k,v]of Object.entries(GOODS)){g.stock[k]=v.initial;g.avg[k]=v.cost;}return g;}

function normalizeSaveV4(s){const old=s.version<4;s.boost??=0;s.regulars??=PEOPLE.map(()=>0);s.event??=eventForDay(s.day);s.puddles??=[];s.visual??=[];s.weatherClock??=0;if(old){const refund=(s.ownedBoots||[]).reduce((n,b)=>n+(b===1?90:b===2?200:0),0);s.cash+=refund;s.stats.aid+=refund;s.migrationRefund=refund;if(s.task?.item?.key)s.stock[s.task.item.key]++;s.stock.erva*=500;s.avg.erva/=500;for(const d of s.deliveries)if(d.key==='erva')d.qty*=500;const items=[...s.hands,...s.kitchen.grill,...s.kitchen.parking,s.kitchen.press,...s.floor.map(f=>f.item),...s.groups.flatMap(g=>g.delivered||[])];for(const i of items.filter(Boolean))if(i.pid==='erva')i.weight=500;else if(i.pid==='cerveja')i.sealed=false;for(const c of s.shop){c.path=[];c.dest=null;if(c.pid==='erva')c.grams=500;}s.task=null;s.up.pepino=s.stock.pepino>0;s.player=physicalPositionIn(s.player);for(const g of s.groups){g.dest=null;g.path=[];}s.needsRoutes=true;}delete s.boots;delete s.ownedBoots;delete s.up.boots1;delete s.up.boots2;for(const t of s.tables){const definition=TABLE_DEF.find(d=>d.id===t.id);if(definition)Object.assign(t,definition);}s.version=4;return s;}

function normalizeSave(s){const previous=s.version;s=normalizeSaveV4(s);s.returnedItems??={};s.gear??='feet';s.slow??=0;s.talkCooldown??=PEOPLE.map(()=>0);s.conversations??=PEOPLE.map(()=>0);s.storyCursor??=PEOPLE.map(()=>0);s.dialogue??=null;s.dialogueQueue=[];if(s.dialogue)s.dialogue.life=clamp(Number.isFinite(s.dialogue.life)?s.dialogue.life:15,0,15);s.tournament??=null;s.fightTarget??=null;s.shopVisits??=0;s.stats.breakage??=0;for(const def of TABLE_DEF){let t=s.tables.find(t=>t.id===def.id);if(!t){t={...def,group:null,dirty:false,plates:0};s.tables.push(t);}t.mode??=previous<5&&s.event.id==='truco'?'truco':'restaurant';t.fight??=null;t.fightCooldown??=0;}if(previous<5){for(const k of ['pinhao','bergamota']){s.stock[k]*=250;s.avg[k]/=250;for(const d of s.deliveries)if(d.key===k)d.qty*=250;}const items=[...s.hands,...s.kitchen.grill,...s.kitchen.parking,s.kitchen.press,...s.floor.map(f=>f.item),...s.groups.flatMap(g=>g.delivered||[])];for(const i of items.filter(Boolean))if(['pinhao','bergamota'].includes(i.pid))i.weight??=250;for(const c of s.shop)if(bulk(c.pid)){c.grams??=['pinhao','bergamota'].includes(c.pid)?250:bulk(c.pid).unit;c.challenge??=makeChallenge(c.grams);}for(const g of s.groups)g.trucoAge??=0;s.cardRound=null;if(s.task?.type==='weigh'){s.task.key??='erva';Object.assign(s.task,challengeFields(s.task.requested,s.task.challenge||makeChallenge(s.task.requested)));}}if(!GEAR[s.gear]||(s.gear!=='feet'&&!s.up[s.gear]))s.gear='feet';if(previous<6){s.up.coffee=true;for(const g of s.groups){g.patience=Math.min(ORDER_WAIT,g.patience/Math.max(1,g.maxPatience)*ORDER_WAIT);g.maxPatience=ORDER_WAIT;}}s.dialogueSeen??=[];s.testMode??=false;s.stats.cardStakes??=0;s.stats.cardReturns??=0;if(s.game){s.game.wager??=0;s.game.wagerSettled??=s.game.phase==='over';}s.room??=1;if(!roomUnlocked(s.room,s))s.room=1;s.mateHerb=clamp(Number.isFinite(s.mateHerb)?s.mateHerb:500,0,500);s.tv=!!s.tv||s.day>=2;
for(const field of ['friends','regulars','talkCooldown','conversations','storyCursor']){s[field]??=[];while(s[field].length<PEOPLE.length)s[field].push(0);}
for(const g of s.groups){g.members??=Array.from({length:g.size},(_,i)=>(g.person+i)%6);if(previous<8){g.patience=Math.min(ORDER_WAIT,g.patience/Math.max(1,g.maxPatience)*ORDER_WAIT);g.maxPatience=ORDER_WAIT;}}
if(previous<8)for(const c of s.shop){c.patience=Math.min(COUNTER_WAIT,c.patience/Math.max(1,c.maxPatience)*COUNTER_WAIT);c.maxPatience=COUNTER_WAIT;}
s.bocce??=null;s.stats.bocceStakes??=0;s.stats.bocceReturns??=0;if(s.bocce)s.bocce.paused=true;s.avatarId=PEOPLE.some(p=>p.id===s.avatarId)?s.avatarId:'sadi';s.bodegaName=String(s.bodegaName||'Bodega Do Sadi').slice(0,40);if(s.gear==='horse')s.gear=s.up.bootsBagual?'bootsBagual':s.up.bootsGaucho?'bootsGaucho':'feet';normalizeVisitors(s);for(const g of s.groups)if(['seated','chat'].includes(g.state))ensureDiners(g);s.eventBag??=[];s.nextEvent??=null;s.atCancha??=false;s.tvAwardPending??=false;s.mateEmptyNotified??=false;if(previous<11){fixedTableModes(s);if(s.day===1)s.tables.forEach(t=>t.fight=null);}delete s.combo;delete s.comboTimer;if(previous<12){s.up.trago=true;s.tutorial.guided=false;s.tutorial.complete=true;}sportState(s);for(const c of s.shop)if(c.pid==='cigarro'&&specialOpponent(c.person))c.pid='codorna';if(s.bocce&&!specialOpponent(s.bocce.opponent))s.bocce.opponent=PEOPLE.findIndex(p=>p.id==='manolima');if(s.game?.type==='truco'&&!specialOpponent(s.game.opponent))s.game.opponent=PEOPLE.findIndex(p=>p.id==='badin');s.version=12;return s;}

function save(show=false){if(!started)return;try{localStorage.setItem(G.testMode?TEST_KEY:KEY,JSON.stringify(G));if(show)say('Bodega salva. Até o próximo causo!');}catch(e){say('O navegador bloqueou o salvamento. Mantenha esta aba aberta.');}}

function readSave(testMode=false){try{let s=JSON.parse(localStorage.getItem(testMode?TEST_KEY:KEY));if(([3,4,5,6,7,8,9,10,11,12].includes(s?.version))&&Number.isFinite(s.cash)&&s.player&&s.kitchen&&Array.isArray(s.groups)&&Array.isArray(s.tables)&&Array.isArray(s.hands)){for(const k of Object.keys(GOODS)){if(!Number.isFinite(s.stock[k]))s.stock[k]=GOODS[k].initial;if(!Number.isFinite(s.avg[k]))s.avg[k]=GOODS[k].cost;}s.testMode=testMode;return normalizeSave(s);}if(testMode)return null;const old=JSON.parse(localStorage.getItem('bodega-interior-v1'));if(old&&Number.isFinite(old.cash)&&old.stock){s=fresh();s.stock.erva=GOODS.erva.initial/500;s.avg.erva=GOODS.erva.cost*500;s.cash=old.cash;s.rep=clamp(old.rep||60,35,100);s.xp=old.xp||0;s.day=old.day||1;s.totalServed=old.soldTotal||0;s.stats=stats(s.cash);s.friends=(old.friends||[]).map(f=>f.xp||0);while(s.friends.length<6)s.friends.push(0);for(const[k,v]of Object.entries(s.stock)){const from=old.stock[k]||old.stock[{cigarro:'marca',codorna:'ovos',erva:'erva'}[k]];if(from){s.stock[k]=Math.max(0,from.shelf+from.reserve);s.avg[k]=from.avg||GOODS[k].cost;}}s.up.capacity=!!old.up?.fridge;s.up.table3=!!old.up?.tables;s.up.bacon=s.xp>=350;s.up.coracao=s.xp>=800;s.cosmetic=!!old.cosmetic;s.version=3;s.legacyDebt=(old.friends||[]).reduce((n,f)=>n+(f.debt||0),0);return normalizeSave(s);}return null;}catch(e){return null;}}
