'use strict';

function escapeHTML(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function drawCharacterPortrait(context,sprite,x,y,height){
 const custom=typeof sprite==='object',s=custom?{x:sprite.crop[0],y:sprite.crop[1],w:sprite.crop[2],h:sprite.crop[3]}:SPRITES[sprite%6];
 const width=height*s.w/s.h;context.imageSmoothingEnabled=false;
 context.drawImage(custom?clippedCharacter(sprite):peopleArt,s.x,s.y,s.w,s.h,x-width/2,y-height,width,height);
}
function initializeCharacterChoice(){
 // Sempre começa com o Sadi; outros personagens são liberados pela amizade máxima.
 const c=$('avatarPreview');if(c)drawCharacterPortrait(c.getContext('2d'),0,c.width/2,c.height-6,166);
}
function upgradeCategory(u){if(u.goods||u.id==='cigarro_py')return 'Cardápio e mercadorias';if(u.id.startsWith('table'))return 'Salão';if(GEAR[u.id]||u.id.toLowerCase().includes('mate'))return 'Botas e chimarrão';return 'Cozinha e atendimento';}
function upgradeCatalog(){
 return ['Cardápio e mercadorias','Cozinha e atendimento','Salão','Botas e chimarrão'].map(category=>`<details class="upgrade-category" open><summary>${category}</summary>${UPGRADES.filter(u=>upgradeCategory(u)===category).map(u=>{
  const missing=[];if(!tutorialUpgradeAllowed(u.id))missing.push('concluir a etapa do tutorial');if(bodegaLevel()<(u.level||1))missing.push('nível '+u.level);if(G.rep<u.rep)missing.push('reputação '+u.rep);if(!hasCash(u.cost))missing.push(money(u.cost));if(u.requires&&!G.up[u.requires])missing.push(UPGRADES.find(v=>v.id===u.requires).name);
  return `<div class="upgrade"><h3>${u.name}</h3><p>${u.desc}</p><p>${u.level>1?'Nível '+u.level+' · ':''}Reputação ${u.rep} · ${money(u.cost)}${u.requires?' · requer '+UPGRADES.find(v=>v.id===u.requires).name:''}</p><button class="primary" data-act="upgrade" data-id="${u.id}" ${G.up[u.id]||missing.length?'disabled':''}>${G.up[u.id]?'Já é da casa':missing.length?'Falta: '+missing.join(' + '):u.cost===0?'Instalar grátis':'Comprar melhoria'}</button></div>`;
 }).join('')}</details>`).join('');
}
function guideContent(){
 const count=improvementCount();
 return `<div class="callout"><b>${escapeHTML(G.bodegaName)} · ${PEOPLE.find(p=>p.id===G.avatarId)?.name||'Sadi'}</b><br>${count} melhorias compradas · ${decorCount()} de ${DECOR.length} peças de decoração.<br>Dinheiro compra melhorias; nível, reputação e compras anteriores liberam as opções. Os requisitos ficam visíveis no celular.</div>${achievementsHTML()}
 <div class="callout"><b>Dificuldade por dias</b><br>Dia 1: tutorial, um freguês por vez e sem prazo.<br>Dia 2: mesas de 1 ou 2, um item por pessoa.<br>Dias 3–4: até 3 pessoas e pedidos duplos.<br>Dias 5–6: até 4 pessoas.<br>Dia 7 em diante: até 3 itens por freguês.<br>A mesa de truco atende como as outras. No campeonato, cada mesa recebe duas duplas fixas, que trocam de adversários durante o dia.</div><div class="guide-grid">
 <article class="panel"><span class="tag">Desde o início</span><h3>Atendimento</h3><p>Balcão separado e mesas para até quatro. Cada freguês tem <b>${ORDER_WAIT} s</b> para receber seu pedido; no balcão, ${COUNTER_WAIT} s. A entrega na mesa atende primeiro quem tem menos tempo para aquele produto. Pagamento e gorjeta são individuais.</p></article>
 <article class="panel"><span class="tag">Desde o início</span><h3>Cozinha e comércio</h3><p>Prepare xis, sirva bebidas e pese mercadorias. Comece com codorna, cigarro e erva; compre salame, pinhão, bergamota, café e mais no celular. A prensa também faz torrada após liberar salame.</p><button data-act="help">Receitas e controles</button></article>
 <article class="panel"><span class="tag">A qualquer momento</span><h3>Truco e cacheta</h3><p>Aproxime-se da mesa fixa de truco: Y joga com o especial que está sentado, e E abre cartas quando ela está livre. Com a mesa livre, você convida só quem está na sua agenda de contatos. Truco aceita aposta e cacheta é livre.</p></article><article class="panel"><span class="tag">Economia</span><h3>Despesas e fiado</h3><p>Todo fim de dia: aluguel (sobe com o nível), luz e querosene dos lampiões. O estoque não vence. Fregueses podem pedir fiado: o caderninho fica no celular.</p></article><article class="panel"><span class="tag">Calendário</span><h3>Semana gaúcha</h3><p>O jogo começa numa sexta. Cada dia é um dia da semana e cada semana, um mês. Quarta tem futebol na TV (Gre-Nal a cada três semanas), sábado tem baile ou campeonato de truco. Depois das 18h anoitece: lampiões iluminam o salão.</p></article><article class="panel"><span class="tag">Fim de semana</span><h3>Laçada e costelão</h3><p>Todo sábado, depois de fechar, você vai ao campo laçar pelo menos 3 bois do rebanho (segure E para girar o laço e solte sobre o boi). Cada boi rende 3 mantas. No domingo a bodega vai para o campo: manta no espeto, vire quando o lado no fogo ficar no ponto, retire, leve à tábua e corte no peso pedido. Maionese: ovo + azeite na tigela, batendo com A e D. Compre bois em Celular → Fornecedor → Campo.</p></article>
 <article class="panel"><span class="tag">A qualquer momento</span><h3>Bocha</h3><p>Entre pela porta da parede direita do salão, com a tabuleta CANCHA DE BOCHA. Na cancha aparece Jogar bocha. Quatro bochas por lado, direção e força. Após o tutorial, Mano Lima ensina a jogar. Adversários são personagens especiais. Sua reputação vai de Aprendiz a Lenda; vitórias dão +10 e derrotas tiram 3 pontos. Use Organizar campeonato para disputar uma chave de oito participantes, com inscrição de R$ 10 e prêmio de R$ 80. A chave fica salva. Também há campeonatos jogáveis no menu do truco. Escolha dificuldade e aposta ou treine sem dinheiro. Truco e bocha <b>pausam todo o atendimento</b>; ao sair, você continua de onde parou.</p></article>
 <article class="panel"><span class="tag">Cresça no seu ritmo</span><h3>Equipamentos e decoração</h3><p>Botas, bandeja, chapa, estoque, mesas e mates estão nas melhorias. Algumas pedem um nível mínimo da bodega.</p><p>Bandeira, fogão a lenha, lampiões, gaita, poncho e outras peças estão em <b>Celular → Estética</b>. Compre, exponha ou guarde quando quiser.</p></article>
 <article class="panel"><span class="tag">Todo dia tem prosa</span><h3>Contatos e eventos</h3><p>Os personagens especiais são raros e avisam quando entram pela primeira vez. Só eles viram amigos: com afeto você ganha o contato, recebe presentes e, na amizade máxima, pode jogar com eles. Três atendimentos corretos de qualquer freguês dão gorjeta extra. Acompanhe em <b>Celular → Contatos</b>. Confira o evento sorteado antes de abrir. O primeiro dia é tranquilo; os seguintes não repetem eventos consecutivos. Ao fechar o dia 1, você ganha uma TV em um sorteio; ela aparece na parede nos dias de jogo do Grêmio, do Inter e Gre-Nal. Nos dias seguintes, há 25% de chance de um contato propor bocha com aposta; recusar tira 3 de amizade. Campeões do truco da bodega pagam uma rodada alcoólica. Vitórias na TV também geram rodadas; no Gre-Nal, a torcida perdedora sai. Brigas só em campeonatos ou a partir do dia 5.</p><button data-act="event">Programação do dia</button></article>
 </div><div class="actions"><button class="primary" data-act="close">Voltar à bodega</button><button data-act="planBuy">Abrir fornecedor e melhorias</button></div>`;
}
function gameGuide(){if(G.game||G.bocce)return;openDialog('Guia e progresso',guideContent(),'guide');}
