// Menus, painéis de fornecedor/melhorias, telas de ajuda e boas-vindas
'use strict';

function openDialog(title,html,type='menu'){modal=type;keys.clear();pointerHold=false;$('dialogTitle').textContent=title;$('dialogContent').innerHTML=html;$('overlay').classList.remove('hidden');$('dialogContent').querySelector('button')?.focus();}

function closeDialog(force=false){if(!force&&modal==='sportChallenge'){answerSportChallenge(false);return;}if(modal==='tvAward')G.tvAwardPending=false;if(G.game&&!force){leaveCards();return;}cardInvite=null;modal=null;paused=false;$('overlay').classList.add('hidden');keys.clear();canvas.focus();save();}

function welcome(){if(G.day===1)tutorialWelcome();else gameGuide();}

function help(){openDialog('Receitas e controles',`<div class="callout"><b>WASD / setas</b> andar · <b>E</b> interagir ou segurar · <b>Q</b> soltar · <b>R</b> retirar ingrediente · <b>1 / 2</b> espaço da bandeja · <b>C</b> celular · <b>Y</b> truco · <b>F</b> abastecer mate · <b>Esc</b> pausa.</div>
<details class="rules" open><summary>Cozinha: xis e torrada</summary><p>Coloque pão na bancada. Queijo e salada vão diretamente no pão; carne e ovo precisam da chapa. Complete os ingredientes do xis, pegue a montagem e leve à prensa. R retira o último ingrediente da bancada. Retire comida pronta em até 18 s para não queimar.</p><p>Torrada: depois de comprar salame, ponha pão e salame diretamente na prensa, em qualquer ordem. Espere 6 s e retire. Não usa salada nem chapa.</p><p>Comida no chão dura 10 s; mercadoria fechada, 20 s. Use as bancadas de apoio para guardar.</p></details>
<details class="rules" open><summary>Bebidas, balança e balcão</summary><p>Pegue o produto e leve ao balcão de atendimento. Cerveja de pressão, cachaça e bitter: segure E e solte na faixa verde. Refrigerante sai da geladeira; café exige comprar a cafeteira.</p><p>Erva, pinhão e bergamota: segure E para pesar e solte no valor do pedido. Recomeçar devolve o estoque; a faixa varia de um pedido para outro.</p><p>Pegou algo por engano? Volte à origem e aperte E para devolver o produto do espaço selecionado. O peso e o estado de preparo são preservados. Café, trago, bitter e cerveja de caneca não podem ser devolvidos; itens queimados ou estragados vão para a lixeira.</p></details>
<details class="rules" open><summary>Mesas para quatro e pedidos individuais</summary><p>Leia os pedidos e cronômetros individuais nos balões sobre os fregueses. Cada pessoa tem ${ORDER_WAIT} s, mesmo se pedir dois itens. Entregar um produto atende quem está esperando por ele com menor prazo; completar o pedido paga só aquela pessoa. Uma desistência não cancela o pedido dos outros.</p><p>No campeonato, as duplas pedem bebidas alcoólicas e petiscos. Nos outros dias, a mesa de truco atende como as demais. Limpe uma mesa vazia segurando E por 1 s. A mesa 2 é fixa de truco; campeonatos usam todas para cartas.</p></details>
<details class="rules"><summary>Mate, chuva e brigas</summary><p>A cuia cabe 500 g e consome 100 g por uso. F junto ao balcão de erva repõe do estoque. Segure E na cuia para o impulso; mates melhores ampliam o efeito e combinam com botas. Poças causam lentidão por 8 s: segure E para secar. Para uma briga, aproxime-se, aperte E e complete a sequência indicada.</p></details>
<details class="rules"><summary>Compras, salvamento e modo de testes</summary><p>C abre Fornecedor, Melhorias e Contatos. O tempo continua no celular. Pedidos ao fornecedor chegam em 8 s. Melhorias mostram custo, reputação e pré-requisitos. O progresso salva automaticamente; a versão de testes tem caixa infinito e salvamento separado.</p></details>
<div class="actions"><button data-act="guide">Guia e desbloqueios</button><button data-act="music">Ligar/desligar música</button><button class="primary" data-act="close">Voltar</button></div>`,'help');}

function togglePhone(force){if(G.task?.type==='weigh')abandonWeigh();phoneOpen=typeof force==='boolean'?force:!phoneOpen;keys.clear();pointerHold=false;cancelHold();$('phone').classList.toggle('hidden',!phoneOpen);if(phoneOpen){G.tutorial.phone=true;renderPhone();$('phone').querySelector('button')?.focus();}else canvas.focus();}

function renderPhone(){document.querySelectorAll('[data-act="tab"]').forEach(b=>b.classList.toggle('active',b.dataset.id===phoneTab));$('phoneNote').textContent=walletText()+' · '+(G.phase==='open'||G.phase==='closing'?'expediente em andamento':'organize antes de abrir');const event=`<div class="phone-event"><b>${eventInfo().icon} ${eventInfo().name}</b><p>${eventInfo().desc}</p>${G.event.id==='motos'?'<b>Encomenda · 2 xis + 2 refri · chegada em '+Math.max(0,Math.ceil(50-G.elapsed))+' s</b>':''}<button class="small" data-act="event">Ver programação</button></div>`,deliveries=G.deliveries.map(d=>`<div class="delivery-line">${nameOf(d.key)} +${stockText(d.key,d.qty)} · ${Math.ceil(d.left)} s</div>`).join('');
 if(phoneTab==='supplier')$('phoneContent').innerHTML=event+deliveries+`<div class="phone-cat">${['Cozinha','Bebidas','Balcão'].map(c=>`<button class="${phoneCat===c?'active':''}" data-act="category" data-id="${c}">${c}</button>`).join('')}</div>`+Object.entries(GOODS).filter(([k,v])=>v.cat===phoneCat&&unlocked(k)).map(([k,v])=>{const room=stationCapacity(k)-G.stock[k]-G.deliveries.filter(d=>d.key===k).reduce((n,d)=>n+d.qty,0),qty=Math.max(0,Math.min(v.pack||6,room));return `<div class="supply"><span class="icon">${itemIconHTML(k)}</span><div><b>${nameOf(k)}</b><p>${stockText(k)} / ${stockText(k,stationCapacity(k))}<br>Pacote: ${stockText(k,qty||v.pack||6)}</p></div><button class="primary" data-act="buy" data-id="${k}" ${qty<=0||!hasCash(qty*v.cost)?'disabled':''}>${qty<=0?'Cheio / a caminho':'Comprar · '+money(qty*v.cost)}</button></div>`;}).join('')+`<button class="aid" data-act="aid" ${G.cash>=40||G.aidDay===G.day?'disabled':''}>Ajuda da comunidade · sem dívida</button>`;
 else if(phoneTab==='contacts'){$('phoneContent').innerHTML=contactsPanel();drawContactPortraits();}
 else if(tutorialActive()&&tutorialStep().id==='upgrade')$('phoneContent').innerHTML='<div class="phone-intro"><h3>Sua primeira melhoria</h3><p>Instale a Mesa de tragos gratuitamente e feche o celular com C para continuar.</p></div>'+upgradeCatalog();
 else $('phoneContent').innerHTML=`<div class="phone-intro"><h3>Faça a bodega crescer</h3><p>${improvementCount()} melhorias compradas. Cada 4 compras liberam outro cenário, até a room 5. Escolha a categoria e confira os requisitos.</p><button data-act="guide">Guia e progresso</button><button data-act="rooms">Trocar cenário</button></div>`+gearPanel()+tablePanel()+upgradeCatalog()+`<button class="aid" data-act="save">Salvar progresso</button>`;

}

function orderGoods(key){if(!GOODS[key]||!unlocked(key))return;const pending=G.deliveries.filter(d=>d.key===key).reduce((n,d)=>n+d.qty,0),qty=Math.min(GOODS[key].pack||6,stationCapacity(key)-G.stock[key]-pending);if(qty<=0){say('Estação cheia ou entrega a caminho.');return;}const cost=round(qty*GOODS[key].cost);if(!hasCash(cost)){say('Não há saldo para este pacote.');AudioEngine.bad();return;}spendCash(cost);if(key==='salame'&&!G.toastLesson)G.toastLesson={day:G.day+1,done:false,actor:null};G.stats.purchases+=cost;G.deliveries.push({id:G.next++,key,qty,cost,left:8,total:8});AudioEngine.phone();save();renderPhone();}

function aid(){if(G.cash>=40||G.aidDay===G.day){say('A ajuda fica disponível uma vez por dia quando o caixa cai abaixo de R$ 40.');return;}G.aidDay=G.day;G.cash+=60;G.stats.aid+=60;for(const k of ['pao_xis','burger','ovo','queijo','salada','cachaca','cigarro','codorna','erva']){const n=Math.min(k==='erva'?1000:3,stationCapacity(k)-G.stock[k]);if(n>0){G.avg[k]=G.avg[k]*G.stock[k]/(G.stock[k]+n);G.stock[k]+=n;}}say('A comunidade trouxe R$ 60, mercadorias e ingredientes. Bora recomeçar!');save();renderPhone();}

function buyUpgrade(id){const u=UPGRADES.find(u=>u.id===id);if(!u||u.unavailable||G.up[id])return;if(championshipActive()&&id.startsWith('table')){say('Amplie o salão antes de abrir: as duplas deste campeonato já estão inscritas.');return;}if(!tutorialUpgradeAllowed(id)){say('Sua primeira melhoria será a Mesa de tragos, na etapa do celular.');return;}if(G.rep<u.rep||!hasCash(u.cost)||(u.requires&&!G.up[u.requires])){say(u.requires&&!G.up[u.requires]?'Compre a melhoria anterior primeiro.':'Confira dinheiro e reputação.');AudioEngine.bad();return;}spendCash(u.cost);G.stats.investments+=u.cost;G.up[id]=true;if(id==='salame'&&!G.toastLesson)G.toastLesson={day:G.day+1,done:false,actor:null};G.tutorial.improvement=true;if(['table3','table4'].includes(id)&&G.event.id==='campeonato'&&['open','closing'].includes(G.phase)){const table=G.tables.find(t=>t.unlock===id);table.previousMode=table.mode;table.mode='truco';}if(GEAR[id])G.gear=id;if(u.goods){const k=u.goods,n=GOODS[k].starter||4;G.avg[k]=G.stock[k]?G.avg[k]*G.stock[k]/(G.stock[k]+n):0;G.stock[k]+=n;say(nameOf(k)+' liberado com '+stockText(k,n)+' para começar.');}if(!canWalk(G.player.x,G.player.y)){const goal=physicalGoal(G.player.x,G.player.y);G.player.x=goal.x;G.player.y=goal.y;}if(id==='table3'||id==='table4'||id==='grill3')for(const actor of [...G.shop,...G.groups])if(actor.dest){const goal={...actor.dest};actor.dest=null;setDestination(actor,goal);}if(id==='cigarro_py'){say('Cigarro do Paraguai: agora cada maço vale R$ 18.');}AudioEngine.heart();announceRoomUnlock();save();renderPhone();}

function equipGear(id){if(id==='horse'||!GEAR[id]||(id!=='feet'&&!G.up[id]))return;if(!['prep','closed'].includes(G.phase)){say('Troque de botas antes de abrir ou após fechar.');return;}G.gear=id;save();renderPhone();}

function gearPanel(){return `<div class="upgrade"><h3>Equipamento · ${GEAR[G.gear].name}</h3><p>Velocidade permanente: +${Math.round(movementBonus()*100)}%. Botas dão velocidade permanente; o mate dá um impulso temporário. O cavalo está indisponível.</p><div class="gear-options">${Object.entries(GEAR).filter(([id])=>id!=='horse'&&(id==='feet'||G.up[id])).map(([id,v])=>`<button class="small" data-act="gear" data-id="${id}" ${G.gear===id||!['prep','closed'].includes(G.phase)?'disabled':''}>${v.name}${G.gear===id?' ✓':''}</button>`).join('')}</div></div><div class="upgrade"><h3>${mateStats().name}</h3><p>+${Math.round(mateStats().bonus*100)}% por ${mateStats().duration} s. Segure E na cuia central.</p></div>`;}

function tablePanel(){return `<div class="upgrade"><h3>Mesas da casa</h3><p>Mesa 2 atende normalmente e também permite jogar truco. As demais são de restaurante; campeonatos usam todas para cartas.</p></div>`;}

function toggleTable(){/* Tipos fixos: não há troca manual de mesas. */}
