// Truco Gaúcho: regras, IA e apostas
'use strict';

function trucoRank(c){if(c.r===1&&c.s===0)return 14;if(c.r===1&&c.s===1)return 13;if(c.r===7&&c.s===0)return 12;if(c.r===7&&c.s===2)return 11;return({3:10,2:9,1:8,12:7,11:6,10:5,7:4,6:3,5:2,4:1})[c.r];}

function trucoWinner(results,mano){if(results.length<2)return null;const[a,b,c]=results;if(a===-1){if(b!==-1)return b;return results.length===3?(c===-1?mano:c):null;}if(b===a||b===-1)return a;if(results.length===3)return c===-1?a:c;return null;}

function newTrucoHand(){const g=G.game,d=deck();g.hands=[d.splice(0,3),d.splice(0,3)];g.board=[null,null];g.history=[];g.results=[];g.stake=1;g.lastRaiser=-1;g.pending=null;g.turn=g.mano;g.lead=g.mano;g.phase='play';gameLog(`Nova rodada. ${g.mano===0?'Você é o mão.':PEOPLE[g.opponent].name+' é o mão.'}`);if(g.turn===1)trucoAI();}

function finishTrucoHand(winner,points){const g=G.game;g.score[winner]+=points;g.phase='between';g.pending=null;sportTalk(g,'truco','rodada');gameLog(`${winner===0?'Você ganhou':PEOPLE[g.opponent].name+' ganhou'} ${points} tento(s).`);if(g.score[winner]>=6){g.phase='over';g.winner=winner;rewardGame(winner===0);}save();}

function resolveTrucoTrick(){const g=G.game;if(!g.board[0]||!g.board[1])return;const rank0=trucoRank(g.board[0]),rank1=trucoRank(g.board[1]),win=rank0===rank1?-1:rank0>rank1?0:1;g.history.push([...g.board]);g.results.push(win);gameLog(win===-1?'Vaza empatada.':win===0?'Você levou a vaza.':PEOPLE[g.opponent].name+' levou a vaza.');const winner=trucoWinner(g.results,g.mano);if(winner!==null){finishTrucoHand(winner,g.stake);return;}g.board=[null,null];if(win!==-1)g.lead=win;g.turn=g.lead;if(g.turn===1)trucoAI();}

function trucoAI(skipRaise=false){const g=G.game;if(g?.tutorial)skipRaise=true;if(g.phase!=='play'||g.turn!==1||g.pending)return;const ranks=g.hands[1].map(trucoRank),strength=Math.max(...ranks);if(!skipRaise&&g.stake<4&&g.lastRaiser!==1&&((strength>=11&&Math.random()<.5)||Math.random()<.06)){sportTalk(g,'truco','truco');g.pending={by:1,target:g.stake+1};gameLog(PEOPLE[g.opponent].name+' pediu '+['','','truco','retruco','vale quatro'][g.stake+1]+'!');return;}let idx=0;if(g.board[0]){const target=trucoRank(g.board[0]);const beating=g.hands[1].map((c,i)=>({i,r:trucoRank(c)})).filter(c=>c.r>target).sort((a,b)=>a.r-b.r);idx=beating.length?beating[0].i:ranks.indexOf(Math.min(...ranks));}else idx=g.results.length===0?ranks.indexOf(Math.max(...ranks)):ranks.indexOf(Math.min(...ranks));sportTalk(g,'truco','carta');g.board[1]=g.hands[1].splice(idx,1)[0];gameLog(PEOPLE[g.opponent].name+' jogou '+cardName(g.board[1])+'.');g.turn=0;if(g.board[0])resolveTrucoTrick();}

function playTruco(index){const g=G.game;if(!g||g.type!=='truco'||g.phase!=='play'||g.turn!==0||g.pending||!g.hands[0][index])return;sportTalk(g,'truco','carta');g.board[0]=g.hands[0].splice(index,1)[0];gameLog('Você jogou '+cardName(g.board[0])+'.');if(g.board[1])resolveTrucoTrick();else{g.turn=1;trucoAI();}save();showCards();}

function raiseTruco(){const g=G.game;if(g.phase!=='play'||g.turn!==0||g.pending||g.stake>=4||g.lastRaiser===0)return;sportTalk(g,'truco','truco');const target=g.stake+1,strength=g.hands[1].reduce((n,c)=>n+trucoRank(c),0)/g.hands[1].length;gameLog('Você pediu '+['','','truco','retruco','vale quatro'][target]+'.');if(strength<5&&Math.random()<.75){gameLog(PEOPLE[g.opponent].name+': Não quero.');finishTrucoHand(0,g.stake);}else{g.stake=target;g.lastRaiser=0;gameLog(PEOPLE[g.opponent].name+': Quero!');if(target<4&&strength>9&&Math.random()<.45){g.pending={by:1,target:target+1};gameLog('E pede '+['','','truco','retruco','vale quatro'][target+1]+'!');}}save();showCards();}

function answerTruco(accept){const g=G.game;if(!g.pending)return;if(!accept){gameLog('Você não quis o aumento.');finishTrucoHand(1,g.stake);}else{g.stake=g.pending.target;g.lastRaiser=1;g.pending=null;gameLog('Você: Quero!');if(g.turn===1)trucoAI(true);}if(g.phase!=='over')sportTalk(g,'truco',accept?'aceitar':'correr');save();showCards();}

function showCards(){const g=G.game;if(!g)return;const name=PEOPLE[g.opponent].name,log=`<div class="card-log" aria-live="polite">${g.log.slice(-5).join('<br>')}</div>`;if(g.type==='truco'){const pending=g.pending,active=g.phase==='play';openDialog('Truco gaúcho · '+name,`<div class="row"><span class="tag">Você ${g.score[0]} × ${g.score[1]} ${name}</span><span class="tag">Até 6 tentos</span><span class="tag">Bodega pausada</span><span class="tag">${g.wager?money(g.wager)+' por jogador':'Sem aposta'}</span><span class="tag">Rodada vale ${g.stake}</span></div><div class="cards-table" style="margin-top:15px"><div>${name}</div><div class="cards-row">${g.hands[1].map(()=>cardHTML(null)).join('')}</div><div class="cards-row">${g.history.map((pair,i)=>`<div><small>Vaza ${i+1} · ${g.results[i]===-1?'Empate':g.results[i]===0?'Você':name}</small><div class="cards-row">${pair.map(c=>cardHTML(c,{})).join('')}</div></div>`).join('')}</div>${g.board.some(Boolean)&&active?`<div class="cards-row">${g.board.map((c,i)=>`<div><small>${i===0?'Você':name}</small><div>${c?cardHTML(c,{}):'aguardando'}</div></div>`).join('')}</div>`:''}<div>Sua mão ${active&&!pending?'· escolha uma carta':''}</div><div class="cards-row">${g.hands[0].map((c,i)=>cardHTML(c,{action:'trucoCard',index:i,disabled:!active||!!pending||g.turn!==0})).join('')}</div></div>${log}${wagerSummary(g)}<div class="actions">${pending?`<strong>${name} pede ${['','','truco','retruco','vale quatro'][pending.target]} (${pending.target} tentos).</strong><button class="primary" data-act="trucoAccept">Quero</button><button data-act="trucoDecline">Não quero · ceder ${g.stake}</button>`:active?`<button class="accent" data-act="trucoRaise" ${g.stake===4||g.lastRaiser===0||g.turn!==0?'disabled':''}>${['','Pedir truco','Retruco','Vale quatro','Limite de quatro'][g.stake]}</button><button data-act="trucoFold">Correr · ceder ${g.stake}</button>`:g.phase==='between'?'<button class="primary" data-act="trucoNext">Próxima rodada →</button>':`<strong>${g.winner===0?'Você ganhou a partida!':'Vitória de '+name+'.'}</strong>`}<button data-act="leaveCards">${g.phase==='over'?'Voltar à bodega':'Sair da partida'}</button></div>${trucoRules}`,'game');}if(g.type==='truco')$('dialogContent').querySelector('.cards-table').insertAdjacentHTML('afterend',trucoLessonTip(g)+sportTalkHTML(g));const logEl=$('dialogContent').querySelector('.card-log');if(logEl)logEl.scrollTop=logEl.scrollHeight;}

// Dicas da partida de treino com o Mano Lima.
function trucoLessonTip(g){
 if(!g.tutorial)return '';
 const tip=g.phase==='over'?'Fim do treino! Volte à bodega: o Mano Lima tem uma coisa pra ti.'
  :g.phase==='between'?'Mão encerrada. A partida vai até 6 tentos: aperte Próxima rodada.'
  :g.history.length===0?'Cada mão tem até 3 vazas: leva a mão quem ganhar 2. Clique numa carta para jogar. As mais fortes: 1 de espadas, 1 de bastos, 7 de espadas e 7 de ouros; depois os 3 e os 2.'
  :g.stake===1?'Com carta boa na mão, peça truco: a mão passa a valer 2 tentos (depois retruco 3 e vale quatro 4). Com mão fraca, dá pra correr e ceder só o que vale.'
  :'Truco pedido! Agora a mão vale mais. Ganhe as vazas para levar os tentos.';
 return `<div class="callout"><b>Lição do Mano Lima</b><br>${tip}</div>`;
}
function leaveCards(){const g=G.game;if(!g){closeDialog(true);return;}if(g.phase!=='over'){if(!g.tutorial&&!confirm(g.wager?'Sair agora perde a aposta de '+money(g.wager)+'. Desistir da partida?':'Encerrar esta partida sem recompensa e voltar à bodega?'))return;settleWager(false);g.phase='over';g.winner=1;g.forfeited=true;if(g.type==='truco')settleSport('truco',g,false);}G.game=null;cardInvite=null;save();closeDialog(true);refreshHUD();if(g.bracket)showSportBracket();else if(g.tutorial&&G.phase==='closed'&&G.giftQueue?.length)startGiftVisit();}

function cardsMenu(){if(!started||G.bocce||G.task){say('Termine a ação atual antes de jogar.');return;}if(phoneOpen)togglePhone(false);if(G.game){showCards();return;}cardInvite=null;if(!invitablePeople().length){openDialog('Ninguém pra jogar ainda',noContactsHTML('truco'),'menu');return;}showTrucoOffer(false);}

function showTrucoOffer(seated){const who=seated?`<p><b>${PEOPLE[cardInvite.person].name}</b> puxou uma cadeira na mesa ${cardInvite.tableId+1}. O freguês volta ao atendimento assim que você sair da partida.</p>`:`<label>Convidar da agenda: <select id="opponent">${invitablePeople().map(i=>{const p=PEOPLE[i];return `<option value="${i}">${p.name} · afeto ${G.friends[i]||0}</option>`;}).join('')}</select></label>`;openDialog(seated?'Uma partida com a turma':'Puxa uma cadeira',`<div class="callout"><b>Bodega pausada.</b> Pedidos, chapa, prensa, entregas, poças e brigas ficam congelados durante a partida.</div>${who}<div class="grid"><div class="panel"><h3>Truco gaúcho · 6 tentos</h3><p>Três cartas, blefe e uma partida curta. A aposta vale pela partida inteira.</p><label class="wager-row">Aposta por jogador <select id="trucoWager" aria-label="Aposta por jogador">${WAGER_OPTIONS.map(n=>`<option value="${n}" ${hasCash(n)?'':'disabled'}>${n?money(n):'Sem aposta'}${hasCash(n)?'':' · saldo insuficiente'}</option>`).join('')}</select></label><p>Caixa: <b>${walletText()}</b>. Cada jogador coloca o mesmo valor. Venceu: recebe o dobro, incluindo sua aposta. Perdeu ou desistiu: perde o valor apostado.</p><p>Pedir truco, retruco ou vale quatro muda os tentos; o valor em dinheiro permanece igual.</p><button class="primary" data-act="startTruco">Começar partida</button></div></div><p>As três primeiras partidas do dia rendem amizade e experiência. O resultado da aposta é contabilizado em todas as partidas.</p><div class="actions"><button data-act="sportTournament" data-id="truco">Organizar campeonato de truco</button><button data-act="sportBracket">Ver chave salva</button><button data-act="close">Voltar sem jogar</button></div>${trucoRules}`,'cards');$('dialogContent').closest('.dialog').scrollTop=0;}

function beginTrucoWager(){if(G.game||modal!=='cards')return;const seated=!!cardInvite;if(seated&&!validCardInvite(cardInvite)){say('Esse freguês já não está disponível nesta mesa.');closeDialog(true);return;}const opponent=seated?cardInvite.person:Number($('opponent')?.value),wager=Number($('trucoWager')?.value);if(!specialOpponent(opponent)||!Number.isInteger(opponent)||opponent<0||opponent>=PEOPLE.length||!WAGER_OPTIONS.includes(wager)||!hasCash(wager)){say('Escolha uma aposta que caiba no caixa.');AudioEngine.bad();return;}spendCash(wager);G.stats.cardStakes+=wager;G.game={type:'truco',opponent,tableId:cardInvite?.tableId??null,groupId:cardInvite?.groupId??null,score:[0,0],mano:0,log:[],phase:'play',rewardGiven:false,wager,wagerSettled:false};cardInvite=null;if(wager)gameLog('Cada jogador colocou '+money(wager)+'. Prêmio total: '+money(wager*2)+'.');sportTalk(G.game,'truco','inicio');syncCardReport();newTrucoHand();showCards();save();refreshHUD();}

function syncCardReport(){if(G.phase==='closed'&&G.report){G.report.cardStakes=G.stats.cardStakes;G.report.cardReturns=G.stats.cardReturns;G.report.end=G.cash;}}

function settleWager(won,draw=false){const g=G.game;if(!g||g.type!=='truco'||g.wagerSettled)return;g.wagerSettled=true;g.wagerResult=draw?'draw':won?'win':'loss';const amount=g.wager||0,payout=draw?amount:won?amount*2:0;if(payout){if(!G.testMode)G.cash=round(G.cash+payout);G.stats.cardReturns+=payout;AudioEngine.coins();}if(amount)gameLog(draw?'Aposta devolvida: '+money(amount)+'.':won?'Recebeu '+money(payout)+' · lucro de '+money(amount)+' no truco.':'Aposta perdida: '+money(amount)+'.');syncCardReport();}

function wagerSummary(g){if(!g.wager)return '<p class="wager-note">Partida amistosa · sem aposta.</p>';return `<p class="wager-note">${g.wagerSettled?(g.wagerResult==='win'?'Aposta vencida: '+money(g.wager*2)+' devolvidos ao caixa. Lucro: '+money(g.wager)+'.':g.wagerResult==='draw'?'Empate: aposta devolvida.':'Aposta perdida: '+money(g.wager)+'.'):'Sua aposta de '+money(g.wager)+' já está na mesa. Prêmio total: '+money(g.wager*2)+'. Sair antes do fim perde a aposta.'}</p>`;}

function rewardGame(won,draw=false){const g=G.game;if(g.rewardGiven)return;settleWager(won,draw);g.rewardGiven=true;if(g.type==='truco')settleSport('truco',g,won);if(G.cardRewards<3){G.cardRewards++;addFriendship(g.opponent,won?5:2);G.xp+=won?22:draw?10:7;gameLog(won?'Boa partida! +22 experiência e +5 amizade.':'A companhia valeu: experiência e +2 amizade.');}else gameLog('As recompensas de hoje já foram recebidas. A prosa continua.');if(won){G.cardWins++;if(G.cardWins>=3&&!G.cosmetic){G.cosmetic=true;gameLog('Estrela dourada desbloqueada para o avental!');}}save();refreshHUD();}

function startTruco(){beginTrucoWager();}

function seatedTrucoTable(){return availableTables().filter(t=>isTableTruco(t)&&t.group&&distRect(G.player,t)<=85&&G.groups.some(g=>g.id===t.group&&['seated','chat'].includes(g.state))).sort((a,b)=>distRect(G.player,a)-distRect(G.player,b))[0]||null;}

function validCardInvite(invite){if(!invite)return false;const t=G.tables.find(t=>t.id===invite.tableId),g=G.groups.find(g=>g.id===invite.groupId);return !!(t&&g&&t.group===g.id&&g.table===t.id&&isTableTruco(t)&&!t.fight&&['seated','chat'].includes(g.state)&&distRect(G.player,t)<=85&&Array.from({length:g.size},(_,j)=>groupPerson(g,j)).includes(invite.person));}

function joinSeatedTruco(){if(!started||paused||modal||phoneOpen)return;if(G.game){showCards();return;}if(G.task){say('Termine a ação antes de puxar uma cadeira.');return;}const table=seatedTrucoTable();if(!table){const near=nearTrucoTable();if(near&&!near.fight)cardsMenu();else say('Chegue perto da mesa de truco para jogar.');return;}if(table.fight){say('Aparte a briga com E antes de jogar com a turma.');return;}const group=G.groups.find(g=>g.id===table.group),person=personCandidates().filter(c=>c.actor.id===group.id&&c.table?.id===table.id).sort((a,b)=>Math.hypot(a.x-G.player.x,a.y-G.player.y)-Math.hypot(b.x-G.player.x,b.y-G.player.y))[0]?.person??group.person;if(!specialOpponent(person)){cardInvite=null;showTrucoOffer(false);return;}cardInvite={tableId:table.id,groupId:group.id,person};G.dialogue=null;G.fightTarget=null;updateDialogue();updateFightUI();showTrucoOffer(true);}

function cardHTML(c,{action='',index=0,disabled=false}={}){if(!c)return'<span class="card back" aria-label="Carta virada"></span>';const rank=c.r,suit=['Espadas','Bastos','Ouros','Copas'][c.s],tag=action?'button':'span';return`<${tag} class="card ${c.s>=2?'red':''} " ${action?`data-card="true" data-act="${action}" data-id="${index}" ${disabled?'disabled':''}`:''} aria-label="${cardName(c)}">${rank}<span>${['♠','♣','♦','♥'][c.s]}</span><small>${suit}</small></${tag}>`;}

function gameLog(t){G.game.log.push(t);G.game.log=G.game.log.slice(-12);}
