// Minijogo de contenção de brigas nas mesas (QTE)
'use strict';

function triggerFight(t){if(!fightsAllowed()||!t||t.fight||!t.group||(!isTableTruco(t)&&G.event.id!=='grenal')||G.tables.some(t=>t.fight))return false;const g=G.groups.find(g=>g.id===t.group);if(!g||g.size<2||!['seated','chat'].includes(g.state))return false;t.fight={left:24,total:24,seq:Array.from({length:['campeonato','grenal'].includes(G.event.id)?10:G.day>=6?9:8},()=>pick(['w','a','s','d'])),step:0,damage:Math.min(45,20+Math.floor(G.day/3)*5),taunt:G.event.id==='grenal'?pick(['Foi impedimento, chê!','Esse juiz precisa de óculos!','Baixa a bola, vivente!']):pick(['Seu chinelão!','Tu tá contando carta, vivente!','Baixa esse berro, bagual!']),age:0};AudioEngine.warning();say('Discussão na mesa '+(t.id+1)+'! Chegue perto e aperte E para apartar.');save();return true;}

function beginFight(t){if(!t?.fight)return;if(distRect(G.player,t)>85){say('Chegue perto da mesa para separar.');return;}if(G.task){say('Termine a ação atual primeiro.');return;}G.fightTarget=t.id;keys.clear();pointerHold=false;updateFightUI();}

function fightKey(key){const t=G.tables.find(t=>t.id===G.fightTarget),f=t?.fight;if(!f)return;if(distRect(G.player,t)>100){G.fightTarget=null;updateFightUI();return;}const mapped={ArrowUp:'w',ArrowLeft:'a',ArrowDown:'s',ArrowRight:'d'}[key]||key;if(!['w','a','s','d'].includes(mapped))return;if(mapped===f.seq[f.step]){f.step++;AudioEngine.tick();if(f.step===f.seq.length){resolveFight(t,true);return;}}else{f.step=0;f.left=Math.max(0,f.left-1);AudioEngine.bad();effect('Calma! Recomece a sequência',t.x+t.w/2,t.y-85,'#ffd195');}updateFightUI();}

function resolveFight(t,success){const f=t.fight;if(!f)return;const g=G.groups.find(g=>g.id===t.group);t.fight=null;t.fightCooldown=['campeonato','grenal'].includes(G.event.id)?10:22;G.fightTarget=null;if(success){G.rep=clamp(G.rep+1,0,100);if(g){for(let j=0;j<g.size;j++){const p=groupPerson(g,j);G.friends[p]=Math.min(100,G.friends[p]+2);}ensureDiners(g);for(const d of g.diners)if(d.status==='waiting')d.patience=Math.min(d.maxPatience,d.patience+18);syncGroupOrders(g);g.trucoAge=0;}effect('Paz na mesa! ♥',t.x+t.w/2,t.y-70,'#e0ffae');AudioEngine.heart();}else{spendCash(f.damage);G.stats.breakage+=f.damage;G.rep=clamp(G.rep-2,0,100);t.plates=Math.max(1,t.plates);if(g)departGroup(g,true);t.dirty=true;effect('Louça quebrada: −'+money(f.damage),t.x+t.w/2,t.y-80,'#ffae88');AudioEngine.trash();say('A briga causou '+money(f.damage)+' de prejuízo. Limpe a mesa para reabrir.');}updateFightUI();save();}

function updateFightUI(){const t=G.tables.find(t=>t.id===G.fightTarget),f=t?.fight;$('fightUI').classList.toggle('hidden',!f);if(!f)return;$('fightTitle').textContent='Apartar a briga · mesa '+(t.id+1);$('fightTime').textContent=Math.ceil(f.left)+' s · risco de '+money(f.damage);$('fightSequence').innerHTML=f.seq.map((k,i)=>'<span class="fight-key '+(i<f.step?'done':i===f.step?'next':'')+'">'+k.toUpperCase()+'</span>').join('');}
