// Mecânicas de cozinha: chapa, prensa de xis, bancadas, balança de secos e lixeira
'use strict';

function putHeld(item){if(held())return false;G.hands[G.slot]=item;return true;}

function takeHeld(){const h=held();G.hands[G.slot]=null;return h;}

function takeFromBin(key){if(!freeHand()){say('Seu espaço ativo está ocupado. Use o apoio, Q ou outro espaço da bandeja.');return;}const item=consumeStock(key);if(item){putHeld(item);AudioEngine.tick();save();}}

function readyProduct(key){if(!freeHand()){say('Libere o espaço ativo da bandeja.');return;}const item=consumeStock(key,'product');if(item){item.pid=key;item.ready=true;item.sealed=!!GOODS[key].sealed;putHeld(item);AudioEngine.glass();burst(G.player.x,G.player.y- 40);save();}}

function mergeLife(a,b){if(b.floorLeft!==null&&b.floorLeft!==undefined)a.floorLeft=a.floorLeft===null||a.floorLeft===undefined?b.floorLeft:Math.min(a.floorLeft,b.floorLeft);}

function dropItem(){if(!started||modal||phoneOpen)return;if(G.task){say('Solte E antes de largar o item.');return;}const i=held();if(!i){say('O espaço selecionado está vazio.');return;}const p=G.player,dx=p.dx||0,dy=p.dy||1,candidates=[{x:p.x+dx*43,y:p.y+dy*43},{x:p.x+dx*39+dy*24,y:p.y+dy*39-dx*24},{x:p.x+dx*39-dy*24,y:p.y+dy*39+dx*24}];const pos=candidates.find(q=>canWalk(q.x,q.y)&&!G.floor.some(f=>Math.hypot(f.x-q.x,f.y-q.y)<32));if(!pos){AudioEngine.bad();effect('Sem espaço',p.x,p.y-50,'#ffb8a1');say('Não há lugar livre à frente. O item continua nas mãos.');return;}takeHeld();i.floorLeft??=i.sealed?20:10;G.floor.push({id:G.next++,item:i,...pos});AudioEngine.drop();burst(pos.x,pos.y);save();refreshHUD();}

function pickupFloor(f){if(!freeHand()){say('Libere o espaço ativo para recolher.');return;}const n=G.floor.indexOf(f);if(n<0)return;G.floor.splice(n,1);putHeld(f.item);AudioEngine.tick();save();}

function trash(){if(!held()){say('Pegue o objeto e traga à lixeira.');return;}const i=takeHeld();G.stats.waste+=i.cost;AudioEngine.trash();effect('Descartado',G.player.x,G.player.y-48,'#dcc8a4');AudioEngine.tick();save();}

function consumeStock(key,kind='ingredient'){if(!unlocked(key)||G.stock[key]<=0){say('Acabou '+nameOf(key)+'. Peça pelo celular: C.');return null;}const cost=G.avg[key],returned=G.returnedItems?.[key]?.shift();G.stock[key]--;if(returned){G.avg[key]=G.stock[key]>0?Math.max(0,(cost*(G.stock[key]+1)-returned.cost)/G.stock[key]):GOODS[key].cost;return {...returned,kind};}return{id:G.next++,kind,key,cost:G.avg[key],heat:0,ready:false,burned:false,spoiled:false,floorLeft:null,cheese:false};}

function useGrill(index){const grill=G.kitchen.grill,h=held(),i=grill[index];if(h?.spoiled||h?.burned){say('Esse ingrediente não pode ser usado. Leve à lixeira.');return;}if(h?.key==='queijo'&&h.kind==='ingredient'){if(!i||!['burger','coracao'].includes(i.key)||i.cheese||i.burned||i.spoiled){say('O queijo vai sobre a carne que está na chapa.');return;}i.cheese=true;i.cost+=h.cost;mergeLife(i,h);takeHeld();AudioEngine.tick();save();return;}if(!i&&h?.kind==='ingredient'&&COOK[h.key]&&!h.ready){grill[index]=takeHeld();grill[index].heat=0;AudioEngine.sizzle();save();return;}if(i&&freeHand()){if(!i.ready&&!i.burned){effect('Ainda cozinhando',G.player.x,G.player.y-50);return;}putHeld(i);grill[index]=null;save();return;}say(i?'Retire com as mãos livres ou adicione queijo à carne.':'Traga carne ou ovo cru para este espaço da chapa.');}

function benchParts(b){return b?b.items.flatMap(i=>[i.key,...(i.cheese?['queijo']:[])]):[];}

function matchRecipe(parts){const sorted=[...parts].sort().join('|');return Object.keys(RECIPES).find(k=>(!RECIPES[k].unlock||G.up[RECIPES[k].unlock])&&[...RECIPES[k].parts].sort().join('|')===sorted);}

function useBench(index){const b=G.kitchen.bench[index],h=held();if(h?.spoiled||h?.burned){say('Ingrediente estragado ou queimado vai para a lixeira.');return;}if(h){if(h.kind!=='ingredient'){say('Esta é a montagem. Itens prontos podem ficar no apoio.');return;}if(!b){if(h.key!=='pao_xis'){say('Primeiro coloque um pão de xis nesta bancada.');return;}G.kitchen.bench[index]={items:[takeHeld()],age:0};AudioEngine.tick();save();return;}if(h.key==='pao_xis'||benchParts(b).includes(h.key)||(h.cheese&&benchParts(b).includes('queijo'))){say('Esse ingrediente já está no xis. R retira o último ingrediente.');return;}if(COOK[h.key]&&!h.ready){say('Cozinhe esse ingrediente na chapa primeiro.');return;}b.items.push(takeHeld());AudioEngine.chop();burst(G.player.x,G.player.y-40);save();return;}if(!b){say('Pegue um pão e coloque aqui com E.');return;}if(!benchParts(b).includes('salada')){const item=consumeStock('salada');if(item){item.ready=true;b.items.push(item);AudioEngine.chop();save();}return;}const pid=matchRecipe(benchParts(b));if(!pid){effect('Faltam ingredientes',G.player.x,G.player.y-52);say('Complete com carne, ovo e queijo. R retira o último ingrediente.');return;}const item={id:G.next++,kind:'assembled',pid,key:pid,parts:benchParts(b),cost:b.items.reduce((n,i)=>n+i.cost,0),perfect:b.items.every(i=>!COOK[i.key]||i.heat<COOK[i.key]+18),floorLeft:null,burned:false,spoiled:false};for(const i of b.items)mergeLife(item,i);G.kitchen.bench[index]=null;putHeld(item);AudioEngine.tick();save();}

function removeIngredient(){if(modal||phoneOpen||G.task)return;const n=nearest();if(n?.kind!=='station'||!n.id.startsWith('bench:')||!freeHand())return;const index=Number(n.id.split(':')[1]),b=G.kitchen.bench[index];if(!b)return;putHeld(b.items.pop());if(!b.items.length)G.kitchen.bench[index]=null;save();}

function usePress(){const p=G.kitchen.press,h=held();if(useToastPress(p,h))return;if(p){if(!freeHand()){say('Libere um espaço para retirar o lanche.');return;}if(!p.ready){effect('Prensando…',G.player.x,G.player.y- 50);return;}G.kitchen.press=null;p.kind='product';p.perfect=p.perfect&&p.heat<22;putHeld(p);AudioEngine.tick();save();return;}if(!h||h.kind!=='assembled'||h.spoiled||h.burned){say('Traga um xis montado ou, com salame desbloqueado, pão e salame para uma torrada.');return;}G.kitchen.press=takeHeld();G.kitchen.press.heat=0;G.kitchen.press.ready=false;AudioEngine.press();save();}

function useToastPress(p,h){if(p?.waitingToast){if(!h){delete p.waitingToast;G.kitchen.press=null;putHeld(p);AudioEngine.tick();save();return true;}const needed=p.key==='pao_xis'?'salame':'pao_xis';if(h.key!==needed||h.spoiled||h.burned){say('Falta '+nameOf(needed)+'. Com mãos vazias, E recupera o ingrediente.');return true;}const second=takeHeld(),item={id:G.next++,kind:'assembled',pid:'torrada',key:'torrada',cost:p.cost+second.cost,parts:['pao_xis','salame'],heat:0,ready:false,perfect:true,burned:false,spoiled:false,floorLeft:null};mergeLife(item,p);mergeLife(item,second);G.kitchen.press=item;AudioEngine.press();effect('Torrada na prensa!',G.player.x,G.player.y-90);save();return true;}if(!p&&unlocked('salame')&&h&&['pao_xis','salame'].includes(h.key)&&['ingredient','product'].includes(h.kind)&&!h.spoiled&&!h.burned){G.kitchen.press=takeHeld();G.kitchen.press.waitingToast=true;AudioEngine.tick();say('Agora coloque '+nameOf(h.key==='pao_xis'?'salame':'pao_xis')+' na prensa.');save();return true;}return false;}

function useParking(index){const old=G.kitchen.parking[index],h=held();G.kitchen.parking[index]=h;G.hands[G.slot]=old;if(!old&&!h)effect('Apoio livre',G.player.x,G.player.y-48);else AudioEngine.tick();save();}

function kitchenTick(dt){for(let j=0;j<G.kitchen.grill.length;j++){const i=G.kitchen.grill[j];if(!i)continue;i.heat+=dt;if(i.heat>=COOK[i.key]&&!i.ready){i.ready=true;AudioEngine.ready();effect('Pronto! Retire da chapa',77,315+j*78,'#d9ffa3');}if(i.heat>=COOK[i.key]+9&&!i.warned){i.warned=true;AudioEngine.warning();effect('Vai queimar!',77,315+j*78,'#ffc875');}if(i.heat>=COOK[i.key]+18&&!i.burned){i.burned=true;AudioEngine.bad();effect('Queimou!',77,315+j*78,'#ff9872');}}const p=G.kitchen.press;if(p&&!p.waitingToast){p.heat+=dt;if(p.heat>=6&&!p.ready){p.ready=true;AudioEngine.ready();effect('Pronto: '+nameOf(p.pid),85,571,'#dcffad');}if(p.heat>=15&&!p.warned){p.warned=true;AudioEngine.warning();effect('Tire da prensa!',85,571,'#ffcb75');}if(p.heat>=24&&!p.burned){p.burned=true;AudioEngine.bad();effect('Lanche queimado!',85,571,'#ff9d75');}}for(const b of G.kitchen.bench)if(b)b.age+=dt;}

function startWeigh(key='erva',target='bag'){if(!freeHand()){say('Libere um espaço para o pacote.');return;}const c=G.shop.find(c=>c.state==='queue'&&c.pid===key),requested=c?.grams||bulk(key).unit;if(G.stock[key]<requested){say('Falta '+nameOf(key)+'. Reponha pelo celular.');return;}const challenge=c?.challenge||(c?(c.challenge=makeChallenge(requested)):makeChallenge(requested));G.task={type:'weigh',key,target,grams:0,orderId:c?.id||null,unitCost:G.avg[key],mode:'fill',time:0,...challengeFields(requested,challenge)};$('weighUI').classList.remove('hidden');updateWeightUI();}

function updateWeightUI(){const t=G.task;if(t?.type!=='weigh')return;$('weighTitle').textContent='Pesar '+nameOf(t.key);$('weightTarget').textContent='Pedido: '+formatWeight(t.requested)+' · '+['faixa larga','faixa média','faixa estreita'][t.challenge.level];$('weightReadout').textContent=formatWeight(t.grams);$('weightFill').style.width=Math.min(100,t.grams/t.maxWeight*100)+'%';$('weightBand').style.left=((t.requested-t.tolerance)/t.maxWeight*100)+'%';$('weightBand').style.width=(t.tolerance*2/t.maxWeight*100)+'%';$('weightReadout').classList.toggle('good',Math.abs(t.grams-t.requested)<=t.tolerance);$('weightStatus').textContent=t.mode==='review'?'Fora da faixa. Recomece: todo o conteúdo volta ao estoque.':'Solte na faixa verde: '+formatWeight(t.requested-t.tolerance)+' a '+formatWeight(t.requested+t.tolerance)+'.';$('weightHold').disabled=t.mode==='review';}

function finishWeigh(){const t=G.task;if(t?.type!=='weigh'||t.mode!=='fill'||t.grams<1)return;const diff=Math.abs(t.grams-t.requested);if(diff>t.tolerance){t.mode='review';AudioEngine.bad();updateWeightUI();return;}const item={id:G.next++,key:t.key,pid:t.key,kind:'product',weight:round(t.grams),requested:t.requested,tolerance:t.tolerance,cost:t.grams*t.unitCost,ready:true,sealed:t.key==='erva',perfect:diff<t.tolerance*.3,floorLeft:null};putHeld(item);G.task=null;$('weighUI').classList.add('hidden');AudioEngine.scaleDone();burst(G.player.x,G.player.y-40,'leaf');effect(formatWeight(item.weight)+' · no capricho!',G.player.x,G.player.y-100,'#e1ff9e');save();}

function abandonWeigh(){const t=G.task;if(t?.type!=='weigh')return;refundWeight(t);G.task=null;$('weighUI').classList.add('hidden');keys.delete('e');pointerHold=false;save();}

function refundWeight(t){const k=t.key||'erva',units=G.stock[k];if(units+t.grams>0)G.avg[k]=(units*G.avg[k]+t.grams*t.unitCost)/(units+t.grams);G.stock[k]+=t.grams;}

function restartWeigh(){const t=G.task;if(t?.type!=='weigh')return;refundWeight(t);t.grams=0;t.unitCost=G.avg[t.key];t.mode='fill';t.time=0;keys.delete('e');pointerHold=false;updateWeightUI();AudioEngine.tick();save();}

function makeChallenge(requested){const level=pick([0,1,2]),width=[.12,.07,.035][level],center=.38+Math.random()*.43;return {level,width,center,tolerance:Math.max(10,Math.round(requested*width)),maxWeight:Math.ceil(requested/center)};}

function challengeFields(requested,challenge){return {challenge,tolerance:challenge.tolerance,maxWeight:challenge.maxWeight,requested};}

function weightTolerance(n,challenge){return challenge?.tolerance||Math.max(10,n*.07);}

function startHold(type,target){if(G.task)return;if(type==='bag'){startWeigh('erva',target);return;}if(['clean','mate','mop'].includes(type)){if(type==='mate'&&G.mateHerb<100){say('Acabou seu mate, traga mais erva para sua cuia.');return;}if(type==='mate'&&held()){say('Apoie o pedido para tomar chimarrão.');return;}G.task={type,target,time:0};return;}if(!freeHand()){say('Libere um espaço para o copo.');return;}const key=type==='coffee'?'cafe':target==='bitter'?'bitter':target==='tap:cerveja'?'cerveja':'cachaca',item=consumeStock(key,'product');if(!item)return;item.pid=key;item.sealed=false;G.task={type:type==='coffee'?'coffee':'pour',target,time:0,item};if(type!=='coffee'){$('pourUI').querySelector('b').textContent=key==='cerveja'?'Cerveja de pressão · espuma no ponto':'Dose no ponto';$('pourUI').classList.remove('hidden');}}

function cancelHold(){const t=G.task;if(!t)return;if(t.type==='weigh'){finishWeigh();return;}if(t.type==='pour'){finishPour();return;}if(t.type==='coffee')G.stock.cafe++;G.task=null;$('pourUI').classList.add('hidden');}

function holdTick(dt){const t=G.task;if(!t)return;const n=nearest(),holding=keys.has('e')||pointerHold;if(t.type==='weigh'){if(phoneOpen||!n||n.id!==t.target){abandonWeigh();return;}if(t.mode==='fill'&&holding){const delta=Math.min(t.maxWeight/2.5*dt,G.stock[t.key],Math.max(0,t.maxWeight-t.grams));G.stock[t.key]-=delta;t.grams+=delta;t.time+=dt;if(t.time>.13){t.time=0;AudioEngine.grain();}updateWeightUI();}return;}if(!holding||phoneOpen||!n||n.id!==t.target){cancelHold();return;}t.time+=dt;if(t.type==='pour'){$('pourFill').style.width=Math.min(100,t.time/1.65*100)+'%';if(t.time>1.8)finishPour();}else if(t.type==='coffee'&&t.time>=1.4){t.item.ready=true;t.item.perfect=true;putHeld(t.item);G.task=null;AudioEngine.glass();effect('Café passado!',G.player.x,G.player.y-100);save();}else if(t.type==='mate'){if(Math.floor(t.time*3)!==Math.floor((t.time-dt)*3))AudioEngine.gulp();if(t.time>=1.1){const m=mateStats();G.boost=m.duration;G.mateHerb=Math.max(0,G.mateHerb-100);G.tutorial.mate=true;notifyEmptyMate();G.task=null;AudioEngine.boost();burst(G.player.x,G.player.y-30,'leaf');effect(m.name+' · '+m.duration+' s',G.player.x,G.player.y-110,'#dcff94');save();}}else if(t.type==='clean'&&t.time>=1){const table=G.tables.find(x=>'table:'+x.id===t.target);if(table?.dirty&&!table.group){table.dirty=false;table.plates=0;effect('Mesa limpa',table.x+table.w/2,table.y-30);burst(table.x+table.w/2,table.y+20);}G.task=null;AudioEngine.clean();assignTables();save();}else if(t.type==='mop'&&t.time>=.8){G.puddles=G.puddles.filter(p=>'puddle:'+p.id!==t.target);G.slow=0;G.task=null;AudioEngine.clean();effect('Piso e pés secos!',G.player.x,G.player.y-90);save();}}

function finishPour(){const t=G.task;if(t?.type!=='pour')return;const fill=t.time/1.65;G.task=null;$('pourUI').classList.add('hidden');if(fill<.15){G.stock[t.item.key]++;return;}if(fill>1.05){G.stats.waste+=t.item.cost;effect('Derramou!',G.player.x,G.player.y-70,'#ffab80');AudioEngine.bad();return;}t.item.ready=true;t.item.perfect=fill>=.68&&fill<=.88;putHeld(t.item);effect(t.item.perfect?'No ponto!':'Dose servida',G.player.x,G.player.y-90,'#d8ffac');AudioEngine.glass();burst(G.player.x,G.player.y-50);save();}
