// Atendimento no balcão, entrega de pedidos nas mesas e pagamentos
'use strict';

function interact(){if(!started||paused||modal||phoneOpen||G.task)return;if(nearCanchaDoor()){enterCancha();return;}const n=nearest();if(!n){effect('Chegue mais perto',G.player.x,G.player.y-52);return;}if(n.kind==='floor'){pickupFloor(n.obj);return;}if(n.kind==='shop'){serveShop(n.obj);return;}if(campoInteract(n))return;if(returnToSource(n.id))return;const[id,arg]=n.id.split(':');if(id==='bin')takeFromBin(arg);else if(id==='bottle')readyProduct(arg);else if(id==='shop'){if(bulk(arg))startWeigh(arg,n.id);else readyProduct(arg);}else if(id==='tap')startHold('pour',n.id);else if(id==='coffee')startHold('coffee',n.id);else if(id==='grill')useGrill(Number(arg));else if(id==='bench')useBench(Number(arg));else if(id==='press')usePress();else if(id==='parking')useParking(Number(arg));else if(id==='trash')trash();else if(id==='bag')startHold('bag',n.id);else if(id==='pour'||id==='bitter')startHold('pour',n.id);else if(id==='mate')startHold('mate',n.id);else if(id==='service')serveCounter(Number(arg)||0);else if(id==='puddle')startHold('mop',n.id);else if(id==='table')interactTable(Number(arg));refreshHUD();}

function interactTable(id){const table=G.tables.find(t=>t.id===id);if(!table)return;if(table.fight){beginFight(table);return;}if(isTableTruco(table)&&!table.group&&!table.dirty){cardsMenu();return;}if(table.dirty&&!table.group){if(held()){say('Libere as mãos e segure E para limpar.');return;}startHold('clean','table:'+id);return;}const g=G.groups.find(g=>g.id===table.group);if(!g){effect('Mesa livre',table.x+table.w/2,table.y-20);return;}if(g.state==='walkTable'){effect('O grupo está chegando',table.x+table.w/2,table.y-20);return;}if(g.state==='chat'){effect('Bah, caprichado!',g.x,g.y-65,'#f9df9b');return;}if(g.state!=='seated')return;const i=held();if(!validForDelivery(i))return;deliverToDiner(g,i,table);}


function serveCounter(index=0){const c=queuedShop()[index];if(!c){say('Balcão livre. Os fregueses entram por aqui.');return;}if(Math.hypot(c.x-c.dest.x,c.y-c.dest.y)>18){say('O freguês está chegando ao balcão.');return;}serveShop(c);}

function pay(items,person,patience,tipOK=true,x=G.player.x,y=G.player.y,credit=false){const revenue=items.reduce((n,i)=>n+salePrice(i),0),cost=items.reduce((n,i)=>n+i.cost,0),perfect=items.some(i=>i.perfect);for(const i of items)if(i.pid==='costela')G.costelaSold=(G.costelaSold||0)+(i.weight||0);G.regulars[person]=(G.regulars[person]||0)+1;const regular=G.regulars[person]>=3,tip=credit?0:tipOK?Math.round(((patience>.35?(perfect?3:1):0)+(regular?2.5:0))*repTips()*2)/2:0;if(credit)recordFiado(person,revenue);else{G.cash=round(G.cash+revenue+tip);G.stats.revenue+=revenue;}G.stats.cogs+=cost;G.stats.tips+=tip;G.stats.served++;G.stats.satisfaction+=clamp(55+patience*40+(perfect?5:0),0,100);G.totalServed++;G.xp+=12+(perfect?5:0);repChange(.25+(patience>.6?.35:patience>.3?.15:0)+(perfect?.2:0));addFriendship(person,2);if(!credit){AudioEngine.register();burst(x,y-40,'coin');showPaymentFeedback(revenue+tip,tip);}if(patience>.6||perfect)fxHearts(x,y-115,perfect?3:2);if(G.regulars[person]===3){say(PEOPLE[person].name+' virou freguês da casa! ♥ Gorjeta extra permanente.');AudioEngine.heart();}save();}

function validForDelivery(i){if(!i||i.kind!=='product'){say('Traga um pedido pronto no espaço selecionado.');return false;}if(i.spoiled||i.burned){say('Esse produto não pode ser servido. Leve à lixeira.');return false;}return true;}
