// Loop de renderização principal do Canvas, camadas e efeitos visuais
'use strict';

// Prepara o canvas e a câmera no mundo 1600 x 900 (usado também pela laçada).
function beginWorld(){const cw=canvas.clientWidth,ch=canvas.clientHeight,dpr=lightGraphics?1:Math.min(Math.max(devicePixelRatio||1,innerWidth>=750?1.5:1),2);if(canvas.width!==Math.round(cw*dpr)||canvas.height!==Math.round(ch*dpr)){canvas.width=Math.round(cw*dpr);canvas.height=Math.round(ch*dpr);}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#20190f';ctx.fillRect(0,0,cw,ch);// Preenche a área útil cortando no máximo ~25% da bodega (a câmera acompanha o jogador); telas muito diferentes de 16:9 ficam com uma faixa mínima.
const fitScale=Math.min(cw/W,ch/H),base=camera.fit?fitScale:Math.min(Math.max(cw/W,ch/H),fitScale*1.35),scale=base*camera.zoom;camera.scale=scale;const viewW=cw/scale,viewH=ch/scale;camera.x=viewW<W?clamp(G.player.x-viewW/2,0,W-viewW):-(viewW-W)/2;camera.y=viewH<H?clamp(G.player.y-viewH*.60,0,H-viewH):-(viewH-H)/2;ctx.scale(scale,scale);ctx.translate(-camera.x,-camera.y);}
function draw(){beginWorld();
 if(isCampo()){drawCampoBackground();drawWeather();}else{const currentRoom=roomArt;if(currentRoom.complete&&currentRoom.naturalWidth){ctx.imageSmoothingEnabled=false;ctx.drawImage(currentRoom,0,0,W,H);ctx.imageSmoothingEnabled=true;}else rect(0,0,W,H,'#7d7955');
 // Signs remain small and belong to the room; the nearby station gets the detailed instruction.

 drawDecor();drawRainWindow();drawNightWindow();drawDecorLights();drawTelevision();drawCanchaDoor();drawWeather();rect(ENTRY.x-70,H-25,139,23,'#624c2e',3,'#ae9253');txt('BEM-VINDO',ENTRY.x,H-14,11,'#d9bd7c');if(G.up.placaFiado&&placaFiadoArt.complete&&placaFiadoArt.naturalWidth){ctx.save();ctx.imageSmoothingEnabled=false;ctx.drawImage(placaFiadoArt,1362,700,96,84);ctx.restore();}}const active=furniture(),near=started&&!modal&&!phoneOpen?nearest():null;
 if(near?.kind==='station'){const f=near.obj;rect(f.x-6,f.y-6,f.w+12,f.h+16,'#ffdb6825',7,'#fce497');}
 // Draw stools first, then furniture and standing people in depth order.
 for(const t of availableTables()){chair(t.x-27,t.y+t.h/2+57);chair(t.x+t.w+27,t.y+t.h/2+57);chair(t.x+32,t.y+t.h+27);chair(t.x+t.w-32,t.y+t.h+27);}
 const layers=active.map(f=>({y:f.y+f.h,draw:()=>furnitureDraw(f)}));
 for(const f of G.floor)layers.push({y:f.y,draw:()=>{ellipse(f.x,f.y+4,20,7,'#37271355');food(f.item.pid||f.item.key,f.x,f.y-11,42,f.item);ctx.strokeStyle=f.item.spoiled?'#ba6944':f.item.floorLeft/(f.item.sealed?20:10)>.55?'#a8cf70':f.item.floorLeft/(f.item.sealed?20:10)>.25?'#f2d16c':'#ee8053';ctx.lineWidth=3;ctx.beginPath();ctx.arc(f.x,f.y-13,25,-Math.PI/2,-Math.PI/2+Math.PI*2*(f.item.spoiled?1:f.item.floorLeft/(f.item.sealed?20:10)));ctx.stroke();txt(f.item.spoiled?'!':Math.ceil(f.item.floorLeft)+'s',f.x,f.y+22,13,f.item.spoiled?'#ffb78a':'#fff5c7');}});
 for(const c of G.shop)layers.push({y:c.y,draw:()=>{if(isSpecial(c.person)&&c.state!=='leave')specialRing(c.x,c.y);personDraw(PEOPLE[c.person].sprite,c.x,c.y,!!c.path?.length,false,c.dx,false,customerMood(c));}});
 for(const g of G.groups){const seated=['seated','chat'].includes(g.state),t=G.tables.find(t=>t.id===g.table);for(let j=0;j<g.size;j++){const {x,y}=groupSeatPosition(g,j);layers.push({y,draw:()=>{const pose=seated&&fightPose(t,x,y,j);if(isSpecial(groupPerson(g,j))&&g.state!=='leave')specialRing(x,y);if(pose)personDraw(PEOPLE[groupPerson(g,j)].sprite,pose.x,pose.y,true,false,pose.dx,false);else personDraw(PEOPLE[groupPerson(g,j)].sprite,x,y,!seated&&(g.state==='tournamentMove'||!!g.path?.length),false,g.dx,seated,dinerMood(g,j));}});}}
 if(deliveryVisitor>0)layers.push({y:ENTRY.y-20,draw:()=>{personDraw(5,ENTRY.x-10,ENTRY.y-20,true);food('erva',ENTRY.x-3,ENTRY.y-71,36);drawDeliveryCrates();}});
 drawChallengeVisit(layers);drawCampoBirds(layers);sceneLayers(layers);layers.push({y:G.player.y,draw:()=>personDraw(avatarSprite(),G.player.x,G.player.y,G.player.walk,true,G.player.dx)});layers.sort((a,b)=>a.y-b.y).forEach(l=>l.draw());
 for(const t of availableTables())if(t.fight)drawBrawl(t);

 drawNight();
 drawCustomerOrders();
 if(G.task?.type==='clean')txt('Limpando…',G.player.x,G.player.y-171,14,'#fff4c4');
 drawFx();drawTutorialArrow();drawActionFeedback();drawSocialFeedback();for(const e of sparks){ctx.globalAlpha=Math.min(1,e.life);txt(e.text,e.x,e.y-(2.2-e.life)*16,15,e.color);}ctx.globalAlpha=1;
 if(near?.kind==='station'){const f=near.obj;rect(f.x+f.w/2-10,f.y+f.h+15,20,21,'#ffdf91',4,'#614322');ctx.fillStyle='#38291b';ctx.font='bold 13px Arial';ctx.textAlign='center';ctx.fillText('E',f.x+f.w/2,f.y+f.h+26);}
 ctx.setTransform(1,0,0,1,0,0);
}

function drawWeather(){for(const p of G.puddles){ellipse(p.x,p.y,p.r,p.r*.36,'#587c8199');ellipse(p.x-5,p.y-2,p.r*.67,p.r*.15,'#b8d7c255');ctx.strokeStyle='#cae1d266';ctx.lineWidth=1;ctx.beginPath();ctx.ellipse(p.x+6,p.y,6+(frameClock*8%11),3,0,0,Math.PI*2);ctx.stroke();}}

function drawActionFeedback(){if(G.boost>0){for(let j=0;j<3;j++){const p=G.player;ellipse(p.x-p.dx*(8+j*10),p.y-p.dy*(8+j*10),12-j*2,4,'#c8e78955');}}for(const v of G.visual){const age=Math.max(0,v.total-v.life),x=v.x+v.dx*age,y=v.y+v.dy*age+20*age*age;ctx.globalAlpha=Math.min(1,v.life*2);if(v.type==='coin'){ellipse(x,y,4,5,'#f6d063');rect(x-1,y-2,2,4,'#a78134');}else if(v.type==='leaf'){ctx.save();ctx.translate(x,y);ctx.rotate(age*5);ellipse(0,0,3,6,'#bfdd7b');ctx.restore();}else{rect(x-2,y-2,4,4,'#fff2bd');}}ctx.globalAlpha=1;for(const t of availableTables().filter(isTableTruco)){if(t.dirty){ellipse(t.x+35,t.y+32,15,8,'#c5bb92');food('cachaca',t.x+75,t.y+29,26);}}if(['mate','mop','clean'].includes(G.task?.type)){const p=G.player;bar(p.x-28,p.y-153,56,G.task.time/(G.task.type==='mate'?1.1:G.task.type==='mop'?.8:1));}}

function drawSocialFeedback(){const p=G.player;if(G.slow>0){txt('Molhado · '+Math.ceil(G.slow)+' s',p.x,p.y+(G.boost>0?44:22),12,'#b9e7f2');}for(const t of availableTables()){txt((t.id+1)+(isTableTruco(t)?' ♠':' ◉'),t.x+t.w-12,t.y+t.h+15,13,isTableTruco(t)?'#e7d69a':'#ddd6b3');}}


function drawExpansionStation(f){if(drawCampoStation(f))return true;if(drawNewStation(f))return true;const{x,y,w,h}=f;
 if(f.id==='mate'){counter(f,'wood');ellipse(x+w/2,y+18,28,15,'#c3b879');rect(x+35,y-24,20,46,'#c9c396',5,'#536143');rect(x+38,y-31,14,9,'#394b35',2);rect(x+51,y-16,11,23,'#69774a',4,'#d2c692');rect(x+39,y-17,4,29,'#fff0bc',2);food('mate',x+ 22,y+17, 40);for(let k=0;k<2;k++){const a=(frameClock*.45+k*.5)%1;ellipse(x+16+k*8+Math.sin(a*7)*3,y-3-a*25,2+a*3,4+a*4,`rgba(255,241,197,${.4*(1-a)})`);}return true;}
 if(f.id.startsWith('tap:')){counter(f,'wood');rect(x+9,y-15,w-18,h-25,'#94632f',12,'#4c3c25');for(let j=0;j<3;j++)rect(x+8,y-6+j*24,w-16,5,'#a2a18c',2,'#5c5f4d');rect(x+w/2-3,y+30,20,7,'#c6c3a1',2,'#535745');rect(x+w/2+10,y+35,6,10,'#c6c3a1',2);food('cerveja',x+w/2+8,y+ 60,35);txt(G.stock.cerveja,x+w/2,y+h-6,13);return true;}
 if(f.id.startsWith('service')){counter(f,'wood');wood(x,y+h-6,w,22,true);rect(x+16,y+7,42,25,'#567459',4,'#364d38');rect(x+20,y+10,30,8,'#d1d7a1',1);for(let j=0;j<3;j++)for(let k=0;k<4;k++)rect(x+20+k*7,y+21+j*4,4,2,'#c9be8e');ellipse(x+w-30,y+22,14,5,'#c4ac61');ellipse(x+w-30,y+17,10,7,'#e2c477');rect(x+w-32,y+5,4,7,'#7f733e');rect(x+80,y+6,47,24,'#d7d0ad',2,'#b0a47e');return true;}
 if(f.id==='bag'){counter(f,'wood');food('erva',x+12,y+9,34);rect(x+20,y+10,28,24,'#aeb197',3,'#5b624e');ellipse(x+34,y+7,17,6,'#c8cbb1');rect(x+23,y+23,21,8,'#33482e',1);txt(G.task?.type==='weigh'?Math.round(G.task.grams):'g',x+34,y+27,8,'#d9efa9');txt((G.stock.erva/1000).toFixed(1)+'kg',x+w/2,y+h-9,11);return true;}
 if(f.id==='bitter'){counter(f);rect(x+12,y-12,21,44,'#753923',5,'#392d1d');rect(x+17,y-24,11,15,'#3b3826',2);rect(x+14,y+2,17,15,'#d5b570',1);food('bitter',x+48,y+24, 30);txt(G.stock.bitter,x+ 22,y+h-8,13);return true;}
 return false;
}

function drawNewStation(f){const{x,y,w,h}=f;if(f.id==='coffee'){counter(f);rect(x+8,y-28,w-16,47,'#aeb8a5',6,'#425048');rect(x+13,y-23,w-26,14,'#3f5849',3);rect(x+22,y-3,7,18,'#514837',2);rect(x+30,y+7,17,5,'#4b4334',2);ellipse(x+w-13,y-11,4,4,'#dcaf56');rect(x+7,y+26,w-14,7,'#4a564a',2);drawCoffeeBrew(x,y,w);food('cafe',x+w/2,y+23,34);if(G.stock.cafe>0)drawCupSteam(x+w/2,y+8);txt(G.stock.cafe,x+13,y+h-8,12);if(G.task?.type==='coffee')bar(x-3,y-42,w+6,G.task.time/1.4);return true;}if(['shop:pinhao','shop:bergamota'].includes(f.id)){const k=f.id.split(':')[1];counter(f,'wood');ellipse(x+w/2,y+15,w*.44,12,'#b8975b');food(k,x+w/2,y+13,42);rect(x+7,y+33,w-14,14,'#3a4c32',2,'#929d6e');txt(formatWeight(G.stock[k]),x+w/2,y+41,10,'#ebefc0');if(G.task?.target===f.id)bar(x-2,y-15,w+4,G.task.grams/G.task.maxWeight);return true;}return false;}

function hintText(n){if(n?.id&&matchingReturn(n.id))return '<strong>E</strong> devolver '+nameOf(sourceProduct(n.id))+' à origem';const expanded=expansionHint(n);if(expanded)return expanded;if(!n)return G.day===1?'<strong>WASD</strong> andar · <strong>E</strong> interagir · <strong>C</strong> comprar':'';if(n.kind==='floor')return'<strong>E</strong> '+n.label+' · '+(n.obj.item.spoiled?'leve à lixeira':Math.ceil(n.obj.item.floorLeft)+' s restantes no chão');if(n.kind==='shop')return'<strong>E</strong> '+n.label+' · '+nameOf(n.obj.pid);const[type,key]=n.id.split(':'),h=held();if(type==='bin'||type==='bottle'||type==='tap'||type==='shop')return'<strong>E</strong> pegar '+nameOf(key)+' · '+G.stock[key]+' na estação';if(type==='bench'){if(h&&h.kind!=='ingredient')return'Leve o pedido pronto ? mesa ou deixe na bancada de apoio.';const b=G.kitchen.bench[Number(key)],missing=RECIPES.xis_salada.parts.filter(k=>!benchParts(b).includes(k));return'<strong>E</strong> '+(h?'adicionar '+nameOf(h.key):!b?'comece pelo pão':matchRecipe(benchParts(b))?'pegar xis montado':!benchParts(b).includes('salada')?'adicionar salada':'faltam '+missing.map(nameOf).join(', '))+' · <strong>R</strong> retirar';}if(type==='grill'){const i=G.kitchen.grill[Number(key)];if(i?.waitingToast)return '<strong>E</strong> adicionar '+nameOf(i.key==='pao_xis'?'salame':'pao_xis')+' à torrada';return'<strong>E</strong> '+(h?.key==='queijo'?'derreter queijo na carne':!i?'colocar carne ou ovo':i.burned?'retirar queimado':i.ready?'retirar '+nameOf(i.key):nameOf(i.key)+' · '+Math.ceil(COOK[i.key]-i.heat)+' s');}if(type==='pour')return'<strong>Segure E</strong> para encher · solte na faixa verde';if(type==='bag')return'<strong>Segure E por 1 s</strong> para ensacar erva-mate';if(type==='parking')return'<strong>E</strong> apoiar / retirar · protegido, sem estragar';if(type==='press')return'<strong>E</strong> '+(!G.kitchen.press?'xis montado ou pão + salame':G.kitchen.press.waitingToast?'adicionar '+nameOf(G.kitchen.press.key==='pao_xis'?'salame':'pao_xis')+' · mãos vazias: recuperar ingrediente':G.kitchen.press.ready?'retirar '+nameOf(G.kitchen.press.pid):'prensando…');if(type==='table'){const t=G.tables[Number(key)],g=G.groups.find(g=>g.id===t.group);return t.dirty?'<strong>Segure E por 1 s</strong> para limpar · mãos livres':g?.state==='seated'?'<strong>E</strong> servir · '+(g.orders.length+' itens na mesa'):g?.state==='chat'?'O grupo está proseando. Logo libera a mesa.':g?'Mesa reservada · grupo chegando':'Mesa livre · '+t.seats+' lugares';}if(type==='cards')return'<strong>E</strong> '+(G.cardRound?'servir '+nameOf(G.cardRound.pid):['prep','closed'].includes(G.phase)?'jogar truco':'a turma está proseando');return'<strong>E</strong> descartar item na lixeira';}

function expansionHint(n){const campo=campoHint(n);if(campo)return campo;if(nearCanchaDoor())return '<strong>E</strong> Entrar na cancha de bocha';if(G.task?.type==='weigh')return '<strong>'+formatWeight(G.task.grams)+' / '+formatWeight(G.task.requested)+'</strong> · solte na faixa verde. Recomeçar devolve o estoque.';if(!n)return null;if(n.id==='mate')return '<strong>Segure E</strong> · '+mateStats().name+' · +'+Math.round(mateStats().bonus*100)+'% por '+mateStats().duration+' s';if(n.id?.startsWith('service')){const c=queuedShop()[Number(n.id.split(':')[1])||0];return c?'<strong>E</strong> entregar a '+PEOPLE[c.person].name+' · '+orderList(c).map(nameOf).join(' + ')+(bulk(c.pid)?' · '+formatWeight(c.grams):'')+(c.fiado?' · pede <b>fiado</b> (E anota · <strong>X</strong> recusa)':''):'Balcão de atendimento · aguarde o próximo freguês';}if(n.id==='bag'){const c=G.shop.find(c=>c.state==='queue'&&c.pid==='erva');return '<strong>Segure E</strong> para pesar '+(c?.grams||500)+' g · '+stockText('erva')+' disponíveis';}if(n.id==='coffee')return '<strong>Segure E por 1,4 s</strong> · passar café';if(n.id==='tap:cerveja')return '<strong>Segure E</strong> · encher caneca · solte na faixa verde';if(n.id?.startsWith('shop:')&&bulk(n.id.split(':')[1]))return '<strong>Segure E</strong> · pesar '+nameOf(n.id.split(':')[1]);if(n.id?.startsWith('table:')){const t=G.tables[Number(n.id.split(':')[1])];if(t.fight)return '<strong>E</strong> apartar a briga · risco de '+money(t.fight.damage);if(isTableTruco(t)&&t.group){const g=G.groups.find(g=>g.id===t.group);if(g&&['seated','chat'].includes(g.state))return '<strong>Y</strong> jogar truco · pausa a bodega · <strong>E</strong> servir'+(g.orders.length?' · '+(g.orders.length+' itens na mesa'):'');}if(!t.group&&!t.dirty)return isTableTruco(t)?'<strong>E</strong> Jogar truco':'Mesa de restaurante · '+t.seats+' lugares';}if(n.id==='bitter')return '<strong>Segure E</strong> para servir bitter · solte na faixa verde';if(n.id?.startsWith('puddle:'))return '<strong>Segure E por 0,8 s</strong> · secar poça para não escorregar';return null;}

function furniture(){if(isCampo())return CAMPO_FIXED.filter(f=>!f.unlock||G.up[f.unlock]);return[...FIXED.filter(f=>!f.unlock||G.up[f.unlock]),...G.tables.filter(t=>!t.unlock||G.up[t.unlock]).map(t=>({...t,id:'table:'+t.id,label:'Mesa '+(t.id+1)}))];}
